import type { Archetype } from '../domain/types.js';
import type { StructuredProfile } from '../domain/scoring/profile.js';
import type { Locale } from './locale.js';

type Translation = Pick<Archetype, 'name' | 'short_description' | 'core_desire' | 'core_fear' | 'core_motivation' | 'strengths' | 'shadow_traits'>;

const es: Record<string, Translation> = {
  innocent: { name: 'Inocente', short_description: 'Confía en la bondad, la claridad y la posibilidad de un camino seguro.', core_desire: 'Conservar la esperanza y actuar de acuerdo con lo que considera bueno', core_fear: 'Perder la confianza o causar daño por una mala elección', core_motivation: 'Crear seguridad, honestidad y una posibilidad de renovación', strengths: ['Percibe posibilidades cuando otros esperan lo peor', 'Aporta sinceridad y claridad a situaciones complejas', 'Ayuda a recuperar la confianza después de una dificultad', 'Mantiene presentes los valores esenciales al decidir'], shadow_traits: ['Puede evitar señales incómodas para conservar la esperanza', 'Puede confiar antes de comprobar si una situación es segura', 'Puede esperar una respuesta sencilla cuando la realidad exige matices'] },
  explorer: { name: 'Explorador', short_description: 'Busca libertad, descubrimiento y una vida elegida con autenticidad.', core_desire: 'Descubrir una vida que se sienta propia', core_fear: 'Quedar atrapado en una vida definida por otros', core_motivation: 'Ampliar horizontes y probar caminos con libertad', strengths: ['Avanza con curiosidad hacia lo desconocido', 'Detecta opciones fuera de la ruta habitual', 'Se adapta con rapidez a nuevos entornos', 'Protege la autonomía al tomar decisiones'], shadow_traits: ['Puede confundir libertad con distancia de todo compromiso', 'Puede abandonar un camino antes de conocer su profundidad', 'Puede buscar el siguiente horizonte para evitar permanecer con una dificultad'] },
  sage: { name: 'Sabio', short_description: 'Busca comprender antes de actuar y convierte la observación en criterio.', core_desire: 'Comprender la verdad y decidir con claridad', core_fear: 'Ser engañado o actuar desde una comprensión incompleta', core_motivation: 'Reunir conocimiento y distinguir lo esencial de lo aparente', strengths: ['Formula preguntas que revelan información útil', 'Reconoce patrones que otros pasan por alto', 'Separa una conclusión de la evidencia que la sostiene', 'Aporta perspectiva antes de una decisión importante'], shadow_traits: ['Puede seguir analizando cuando la situación ya pide acción', 'Puede tomar distancia emocional para sentirse seguro', 'Puede esperar certeza donde solo existe información suficiente'] },
  hero: { name: 'Héroe', short_description: 'Responde al desafío con valor, disciplina y voluntad de actuar.', core_desire: 'Demostrar valor mediante acciones que importan', core_fear: 'No estar a la altura cuando una situación exige coraje', core_motivation: 'Superar obstáculos y convertir el esfuerzo en una contribución real', strengths: ['Da el primer paso cuando otros dudan', 'Sostiene el esfuerzo frente a la dificultad', 'Acepta responsabilidad en momentos decisivos', 'Transforma una intención en acción concreta'], shadow_traits: ['Puede convertir cada dificultad en una prueba personal', 'Puede cargar más de lo necesario para demostrar fortaleza', 'Puede actuar con rapidez sin escuchar límites propios o ajenos'] },
  outlaw: { name: 'Rebelde', short_description: 'Cuestiona límites que han perdido sentido y abre espacio para el cambio.', core_desire: 'Liberarse de restricciones que ya no merecen obediencia', core_fear: 'Ser controlado por una estructura injusta o vacía', core_motivation: 'Romper patrones que impiden una vida más auténtica', strengths: ['Detecta reglas que ya no sirven a su propósito', 'Se atreve a nombrar una verdad incómoda', 'Abre alternativas cuando el sistema se ha vuelto rígido', 'Defiende la libertad frente a una autoridad sin fundamento'], shadow_traits: ['Puede resistirse por reflejo antes de entender la situación', 'Puede destruir una estructura sin preparar lo que vendrá después', 'Puede interpretar toda coordinación como una amenaza a su libertad'] },
  magician: { name: 'Mago', short_description: 'Percibe conexiones ocultas y transforma la manera de entender lo posible.', core_desire: 'Convertir una visión significativa en una transformación real', core_fear: 'Usar la comprensión sin responsabilidad o no poder volverla realidad', core_motivation: 'Relacionar señales, intención y acción para producir cambio', strengths: ['Reconoce conexiones entre elementos que parecen separados', 'Ayuda a cambiar la perspectiva antes de cambiar la acción', 'Convierte símbolos e intuiciones en posibilidades concretas', 'Sostiene una visión cuando todavía no es evidente para otros'], shadow_traits: ['Puede atribuir demasiado significado a una coincidencia', 'Puede prometer una transformación antes de probar el proceso', 'Puede aferrarse a una visión cuando la evidencia pide revisarla'] },
  lover: { name: 'Amante', short_description: 'Da valor a la intimidad, la belleza y la calidad de los vínculos.', core_desire: 'Vivir una conexión profunda con personas, experiencias y valores', core_fear: 'Perder el vínculo o atravesar la vida sin verdadera cercanía', core_motivation: 'Cultivar presencia, pertenencia y compromiso emocional', strengths: ['Escucha lo que una experiencia significa para otra persona', 'Crea vínculos a través de la atención y la presencia', 'Percibe belleza y valor en detalles que otros omiten', 'Protege la calidad humana de una decisión'], shadow_traits: ['Puede ceder demasiado para conservar un vínculo', 'Puede confundir intensidad con compatibilidad', 'Puede tomar la distancia de otra persona como un juicio sobre su propio valor'] },
  creator: { name: 'Creador', short_description: 'Imagina formas nuevas y convierte una visión personal en algo tangible.', core_desire: 'Crear algo auténtico y duradero', core_fear: 'Vivir sin dar forma a sus ideas o producir algo vacío', core_motivation: 'Dar estructura original a una visión significativa', strengths: ['Imagina soluciones que todavía no existen', 'Da forma concreta a ideas abstractas', 'Mejora una experiencia a través del diseño y el detalle', 'Tolera la iteración necesaria para crear algo propio'], shadow_traits: ['Puede posponer el cierre buscando una versión perfecta', 'Puede proteger tanto una idea que deja de recibir aportes', 'Puede vincular su valor personal con el resultado de lo que crea'] },
  caregiver: { name: 'Cuidador', short_description: 'Reconoce lo que necesita apoyo y convierte el cuidado en una acción práctica.', core_desire: 'Ayudar a que las personas y lo importante permanezcan sostenidos', core_fear: 'Ignorar una necesidad cuando su ayuda podría haber importado', core_motivation: 'Sostener a las personas y las condiciones que permiten continuar', strengths: ['Percibe necesidades que un grupo apresurado puede omitir', 'Convierte la ayuda en algo práctico y específico', 'Crea continuidad durante una interrupción', 'Recuerda el costo humano de una decisión'], shadow_traits: ['Puede asumir responsabilidades sin comprobar consentimiento o capacidad', 'Puede dejar sus propias necesidades al final durante demasiado tiempo', 'Puede dificultar que otros contribuyan al encargarse de todo'] },
  jester: { name: 'Bufón', short_description: 'Encuentra movimiento a través del juego, la perspectiva y el presente.', core_desire: 'Experimentar vitalidad y disfrute compartido', core_fear: 'Una vida reducida al deber y sin espacio para jugar', core_motivation: 'Liberar una perspectiva rígida y abrir posibilidades en el presente', strengths: ['Reduce la tensión sin exigir que todo esté resuelto', 'Invita a participar mediante el juego', 'Descubre un ángulo inesperado', 'Mantiene al grupo conectado con el momento presente'], shadow_traits: ['Puede usar el humor para alejarse demasiado pronto de la incomodidad', 'Puede postergar el seguimiento por un momento más atractivo', 'Puede subestimar la seriedad con la que otra persona vive un problema'] },
  ruler: { name: 'Gobernante', short_description: 'Crea orden, dirección y condiciones confiables para una tarea compartida.', core_desire: 'Crear un orden compartido estable y eficaz', core_fear: 'Un fracaso evitable sin responsabilidad clara', core_motivation: 'Coordinar recursos y decisiones hacia un resultado duradero', strengths: ['Aclara responsabilidades cuando un grupo está inseguro', 'Relaciona las tareas inmediatas con un plan mayor', 'Hace visibles los recursos y las consecuencias', 'Construye sistemas capaces de sostener continuidad'], shadow_traits: ['Puede aumentar el control cuando ayudaría construir comprensión compartida', 'Puede considerar otro método como una amenaza a la confiabilidad', 'Puede centralizar las decisiones durante más tiempo del necesario'] },
  everyman: { name: 'Compañero', short_description: 'Construye pertenencia mediante la participación, la cooperación y el terreno común.', core_desire: 'Pertenecer y contribuir junto a otros', core_fear: 'Quedar excluido de la vida compartida', core_motivation: 'Hacer posible la participación sin exigir una posición excepcional', strengths: ['Encuentra terreno común entre personas diferentes', 'Hace que contribuir se sienta accesible', 'Comparte la responsabilidad práctica', 'Percibe cuando alguien está quedando fuera del grupo'], shadow_traits: ['Puede ocultar una diferencia útil para conservar la pertenencia', 'Puede aceptar una norma conocida sin examinarla', 'Puede esperar acuerdo cuando necesita tomar una decisión personal'] },
};

export function localizeArchetype<T extends Archetype>(value: T, locale: Locale): T {
  if (locale === 'en') return value;
  return { ...value, ...es[value.slug] };
}

export function archetypeName(slug: string, fallback: string, locale: Locale) {
  return locale === 'es' ? es[slug]?.name ?? fallback : fallback;
}

export function localizedCharacterTitle(profile: StructuredProfile, locale: Locale) {
  if (locale === 'en') return profile.character.title;
  const woman = profile.user.character_gender === 'woman';
  const titles: Record<string, [string, string]> = {
    innocent: ['El guardián de la esperanza', 'La guardiana de la esperanza'], explorer: ['El caminante de horizontes', 'La caminante de horizontes'], sage: ['El intérprete de señales', 'La intérprete de señales'], hero: ['El portador del valor', 'La portadora del valor'], outlaw: ['El viajero inconforme', 'La viajera inconforme'], magician: ['El tejedor de posibilidades', 'La tejedora de posibilidades'], lover: ['El guardián de los vínculos', 'La guardiana de los vínculos'], creator: ['El forjador de caminos', 'La forjadora de caminos'], caregiver: ['El custodio del refugio', 'La custodia del refugio'], jester: ['El portador de la chispa', 'La portadora de la chispa'], ruler: ['El arquitecto del orden', 'La arquitecta del orden'], everyman: ['El compañero del camino', 'La compañera del camino'],
  };
  return titles[profile.archetypes.primary.slug]?.[woman ? 1 : 0] ?? 'La historia que llevas dentro';
}
