import {
  buildDraftJourney,
  type BilingualSeed,
  type ChoiceSeed,
} from '../draft-authoring.js';
import { councilOfRealmsMetadata } from './metadata.js';

const b = (en: string, es: string): BilingualSeed => [en, es];
const q = (
  textEn: string,
  textEs: string,
  benefitEn: string,
  benefitEs: string,
  costEn: string,
  costEs: string,
): ChoiceSeed => [
  b(textEn, textEs),
  b(benefitEn, benefitEs),
  b(costEn, costEs),
];

export const councilOfRealmsContent = buildDraftJourney({
  id: councilOfRealmsMetadata.id,
  slug: councilOfRealmsMetadata.slug,
  title: b(councilOfRealmsMetadata.title.en, councilOfRealmsMetadata.title.es),
  acts: councilOfRealmsMetadata.acts.map((act) => b(act.en, act.es)),
  scenes: [
    {
      title: b('The Empty Seat', 'El asiento vacío'),
      narrative: b(
        'At dawn, five banners hang above a circular chamber and one chair remains empty. The realm expects the absent regent, yet the chamberlain places the seal before you while every delegate waits to see who will begin.',
        'Al amanecer, cinco estandartes cuelgan sobre una cámara circular y un asiento permanece vacío. El reino espera al regente ausente, pero el chambelán deja el sello frente a ti mientras cada delegado espera quién comenzará.',
      ),
      purpose: b(
        'Open the council with visible uncertainty and establish the protagonist as a temporary participant, not an appointed ruler.',
        'Abrir el consejo con incertidumbre visible y establecer al protagonista como participante temporal, no como gobernante designado.',
      ),
      psychology: b(
        'Observe willingness to coordinate and tolerate interpersonal exposure before authority is formally granted.',
        'Observar la disposición a coordinar y tolerar la exposición interpersonal antes de recibir autoridad formal.',
      ),
      primary: ['leadership_initiative', 'social_confidence'],
      facets: ['responsibility_assumption', 'interpersonal_visibility'],
      contexts: ['public_visibility', 'responsibility'],
      visual: b(
        'A circular stone council chamber at dawn, five banners, one empty high-backed chair, a sealed brass medallion on the table, no readable text.',
        'Una cámara circular de piedra al amanecer, cinco estandartes, un asiento alto vacío y un medallón de bronce sellado sobre la mesa, sin texto legible.',
      ),
      continuity: b(
        'The brass council seal remains on the table and travels through every later chamber scene.',
        'El sello de bronce permanece sobre la mesa y continúa en todas las escenas posteriores de la cámara.',
      ),
      choices: [
        q(
          'Stand, name the uncertainty, and invite each delegate to state what must be decided first.',
          'Te pones de pie, nombras la incertidumbre e invitas a cada delegado a decir qué debe decidirse primero.',
          'Creates movement while making participation visible.',
          'Genera movimiento y hace visible la participación.',
          'Publicly assumes responsibility before legitimacy is settled.',
          'Asume responsabilidad en público antes de que la legitimidad esté resuelta.',
        ),
        q(
          'Ask the chamberlain to collect priorities privately, then arrange the first round yourself.',
          'Pides al chambelán que reúna las prioridades en privado y luego organizas tú la primera ronda.',
          'Coordinates the room with less social exposure.',
          'Coordina la sala con menor exposición social.',
          'May appear distant or overly procedural at a symbolic moment.',
          'Puede parecer distante o demasiado procedimental en un momento simbólico.',
        ),
        q(
          'Speak clearly about the danger of delay, but leave the order of discussion to the senior delegate.',
          'Hablas con claridad sobre el peligro de la demora, pero dejas el orden de discusión al delegado de mayor rango.',
          'Makes a position visible without taking full control.',
          'Hace visible una posición sin tomar el control completo.',
          'Relies on status to produce coordination.',
          'Depende del rango para producir coordinación.',
        ),
        q(
          'Remain seated until the chamber reveals who has recognized authority to convene the council.',
          'Permaneces sentado hasta que la cámara revele quién tiene autoridad reconocida para convocar al consejo.',
          'Avoids creating an illegitimate precedent.',
          'Evita crear un precedente ilegítimo.',
          'The vacuum may harden while everyone waits.',
          'El vacío puede endurecerse mientras todos esperan.',
        ),
      ],
    },
    {
      title: b('Four Claims to One River', 'Cuatro reclamos sobre un río'),
      narrative: b(
        'The first map shows a river feeding four provinces. Drought has narrowed it to a silver thread, and each delegate places a different carved token over the same bend.',
        'El primer mapa muestra un río que alimenta cuatro provincias. La sequía lo ha reducido a un hilo de plata y cada delegado coloca una ficha tallada distinta sobre el mismo recodo.',
      ),
      purpose: b(
        'Introduce the shared resource conflict that drives the Journey.',
        'Introducir el conflicto por recursos compartidos que impulsa el Journey.',
      ),
      psychology: b(
        'Separate organized process from perspective taking when claims cannot all be satisfied.',
        'Separar el proceso organizado de la toma de perspectiva cuando no pueden satisfacerse todos los reclamos.',
      ),
      primary: ['empathy_cooperation', 'structure'],
      facets: ['perspective_taking', 'prioritization'],
      contexts: ['moral_tradeoff', 'resource_scarcity'],
      visual: b(
        'An old relief map of four provinces around a narrow river, four symbolic carved tokens, tense hands, no lettering.',
        'Un mapa antiguo en relieve de cuatro provincias alrededor de un río estrecho, cuatro fichas simbólicas, manos tensas y sin letras.',
      ),
      continuity: b(
        'The river map and four tokens remain the fixed decision surface throughout the council.',
        'El mapa del río y las cuatro fichas siguen siendo la superficie fija de decisión durante el consejo.',
      ),
      choices: [
        q(
          'Ask each province to name what it cannot lose, then order the needs by urgency.',
          'Pides a cada provincia que nombre aquello que no puede perder y luego ordenas las necesidades por urgencia.',
          'Combines perspective taking with a usable sequence.',
          'Combina la toma de perspectiva con una secuencia útil.',
          'Takes time and exposes whose needs rank lower.',
          'Consume tiempo y deja en evidencia qué necesidades quedan más abajo.',
        ),
        q(
          'Let every delegate tell the human cost in full before proposing any order.',
          'Dejas que cada delegado relate por completo el costo humano antes de proponer un orden.',
          'Builds mutual understanding.',
          'Construye comprensión mutua.',
          'May delay action and leave priorities unresolved.',
          'Puede demorar la acción y dejar prioridades sin resolver.',
        ),
        q(
          'Set common criteria for population, harvest and reserves before hearing further appeals.',
          'Estableces criterios comunes de población, cosecha y reservas antes de escuchar más pedidos.',
          'Creates consistency and limits bargaining noise.',
          'Crea consistencia y limita el ruido de las negociaciones.',
          'May miss local consequences the criteria cannot represent.',
          'Puede ignorar consecuencias locales que los criterios no representan.',
        ),
        q(
          'Let each province defend its own claim and see which compromise emerges without a fixed procedure.',
          'Dejas que cada provincia defienda su reclamo y observas qué acuerdo surge sin un procedimiento fijo.',
          'Preserves local voice and spontaneous bargaining.',
          'Conserva la voz local y la negociación espontánea.',
          'Powerful speakers may shape the outcome more than need.',
          'Los oradores más fuertes pueden influir más que la necesidad.',
        ),
      ],
    },
    {
      title: b('The Sealed Ledger', 'El registro sellado'),
      narrative: b(
        'A clerk brings a locked grain ledger. The regent ordered it sealed, yet rumors say the official reserves are overstated and the key will not arrive before night.',
        'Un escriba trae un registro de grano cerrado. El regente ordenó sellarlo, pero los rumores dicen que las reservas oficiales están exageradas y la llave no llegará antes de la noche.',
      ),
      purpose: b(
        'Make imperfect information concrete without changing the fixed route.',
        'Volver concreta la información imperfecta sin alterar el recorrido fijo.',
      ),
      psychology: b(
        'Observe independent judgment and evidence seeking when protocol and urgency conflict.',
        'Observar el juicio independiente y la búsqueda de evidencia cuando el protocolo y la urgencia entran en conflicto.',
      ),
      primary: ['autonomy', 'knowledge_orientation'],
      facets: ['independent_judgment', 'evidence_seeking'],
      contexts: ['authority', 'knowledge_gap'],
      visual: b(
        'A heavy leather ledger sealed with dark wax beside grain measures and an unmarked brass keyhole, no readable writing.',
        'Un pesado registro de cuero sellado con cera oscura junto a medidas de grano y una cerradura de bronce sin inscripciones.',
      ),
      continuity: b(
        'The unopened ledger returns later with the same wax seal and damaged corner.',
        'El registro sin abrir reaparece más adelante con el mismo sello de cera y una esquina dañada.',
      ),
      choices: [
        q(
          'Order witnesses present, break the seal, and verify the stores before debate continues.',
          'Ordenas reunir testigos, rompes el sello y verificas las reservas antes de continuar el debate.',
          'Uses independent judgment to obtain decisive evidence.',
          'Usa el juicio propio para obtener evidencia decisiva.',
          'Breaks protocol and makes you accountable for the breach.',
          'Rompe el protocolo y te hace responsable de la transgresión.',
        ),
        q(
          'Inspect warehouses and shipping marks without opening the regent’s ledger.',
          'Inspeccionas depósitos y marcas de carga sin abrir el registro del regente.',
          'Builds evidence while preserving the formal seal.',
          'Construye evidencia y conserva el sello formal.',
          'The indirect count may remain incomplete.',
          'El recuento indirecto puede seguir incompleto.',
        ),
        q(
          'Ask the council to authorize opening it after hearing every objection on record.',
          'Pides al consejo autorización para abrirlo después de escuchar cada objeción.',
          'Seeks evidence with shared legitimacy.',
          'Busca evidencia con legitimidad compartida.',
          'Independent judgment may be diluted by political pressure.',
          'El juicio propio puede diluirse por presión política.',
        ),
        q(
          'Keep it sealed and work from the figures already certified by the regent.',
          'Lo mantienes cerrado y trabajas con las cifras ya certificadas por el regente.',
          'Preserves institutional continuity.',
          'Conserva la continuidad institucional.',
          'The decision may rest on information nobody has verified.',
          'La decisión puede depender de información que nadie verificó.',
        ),
      ],
    },
    {
      title: b('An Accusation Before Witnesses', 'Una acusación ante testigos'),
      narrative: b(
        'When the bronze doors open to petitioners, a frontier captain accuses the river envoy of hiding supplies. The chamber turns toward you as anger replaces procedure.',
        'Cuando las puertas de bronce se abren a los peticionarios, un capitán de frontera acusa al enviado del río de ocultar suministros. La cámara se vuelve hacia ti mientras la ira reemplaza al procedimiento.',
      ),
      purpose: b(
        'Escalate disagreement in a public setting while preserving a nonviolent conflict.',
        'Escalar el desacuerdo en un entorno público y conservar un conflicto no violento.',
      ),
      psychology: b(
        'Observe assertive participation and functional emotional regulation during accusation.',
        'Observar la participación asertiva y la regulación emocional funcional durante una acusación.',
      ),
      primary: ['social_confidence', 'emotional_regulation'],
      facets: ['disagreement_tolerance', 'composure_under_pressure'],
      contexts: ['interpersonal_conflict', 'public_visibility'],
      pressure: true,
      visual: b(
        'A crowded bronze-doored chamber, two delegates facing each other, petitioners watching, tense but no weapons drawn, no text.',
        'Una cámara concurrida con puertas de bronce, dos delegados enfrentados y peticionarios observando, tensión sin armas desenvainadas ni texto.',
      ),
      continuity: b(
        'The captain and envoy stay in the chamber; no one leaves or begins a side mission.',
        'El capitán y el enviado permanecen en la cámara; nadie se va ni inicia una misión secundaria.',
      ),
      choices: [
        q(
          'Interrupt firmly, acknowledge the anger, and require one claim and one answer at a time.',
          'Interrumpes con firmeza, reconoces la ira y exiges una acusación y una respuesta por turno.',
          'Contains escalation while remaining visibly engaged.',
          'Contiene la escalada y mantiene una participación visible.',
          'May be read as controlling the emotional tone.',
          'Puede interpretarse como un intento de controlar el tono emocional.',
        ),
        q(
          'Lower your voice, pause the witnesses, and question both parties in a smaller circle.',
          'Bajas la voz, haces una pausa con los testigos y preguntas a ambas partes en un círculo reducido.',
          'Protects composure and improves listening.',
          'Protege la calma y mejora la escucha.',
          'Reduces public transparency at a sensitive moment.',
          'Reduce la transparencia pública en un momento sensible.',
        ),
        q(
          'Let the accusation finish publicly, then challenge its unsupported parts directly.',
          'Dejas que la acusación termine en público y luego cuestionas directamente sus partes sin respaldo.',
          'Tolerates exposure and tests the claim openly.',
          'Tolera la exposición y pone a prueba la acusación abiertamente.',
          'The room may absorb more anger before facts emerge.',
          'La sala puede absorber más ira antes de que aparezcan los hechos.',
        ),
        q(
          'Call a recess until tempers fall and ask the chamberlain to resume procedure later.',
          'Convocas un receso hasta que baje la tensión y pides al chambelán retomar el procedimiento después.',
          'Prevents an impulsive ruling.',
          'Evita una resolución impulsiva.',
          'The unresolved accusation may spread outside the room.',
          'La acusación sin resolver puede extenderse fuera de la sala.',
        ),
      ],
    },
    {
      title: b('The Quiet Delegation', 'La delegación silenciosa'),
      narrative: b(
        'Three ward leaders know the river gates better than anyone, but years of rivalry keep them silent. The council wants you to assign one of them command before the first water convoy departs.',
        'Tres líderes de distrito conocen las compuertas mejor que nadie, pero años de rivalidad los mantienen en silencio. El consejo quiere que asignes el mando a uno antes de que parta el primer convoy de agua.',
      ),
      purpose: b(
        'Introduce delegation as a shared-responsibility problem rather than a rank reward.',
        'Introducir la delegación como problema de responsabilidad compartida y no como premio de rango.',
      ),
      psychology: b(
        'Observe coordination initiative alongside coalition building.',
        'Observar la iniciativa de coordinación junto con la construcción de alianzas.',
      ),
      primary: ['leadership_initiative', 'empathy_cooperation'],
      facets: ['delegation', 'coalition_building'],
      contexts: ['group_coordination', 'responsibility'],
      visual: b(
        'Three rival ward leaders around a model of river gates while a water convoy waits beyond an open arch, no text.',
        'Tres líderes rivales alrededor de una maqueta de compuertas mientras un convoy de agua espera tras un arco abierto, sin texto.',
      ),
      continuity: b(
        'All three leaders remain responsible for the same convoy regardless of the coordination method chosen.',
        'Los tres líderes siguen siendo responsables del mismo convoy sin importar el método de coordinación elegido.',
      ),
      choices: [
        q(
          'Give each leader one clear responsibility and require them to name how their parts depend on the others.',
          'Das a cada líder una responsabilidad clara y exiges que expliquen cómo su parte depende de las demás.',
          'Combines delegation with explicit interdependence.',
          'Combina delegación con interdependencia explícita.',
          'Shared work may blur who answers for the final outcome.',
          'El trabajo compartido puede volver difusa la responsabilidad final.',
        ),
        q(
          'Name one commander and ask that person to choose how the other two will contribute.',
          'Nombras a un comandante y le pides que decida cómo contribuirán los otros dos.',
          'Creates a clear line of responsibility.',
          'Crea una línea clara de responsabilidad.',
          'Coalition trust depends heavily on one rival.',
          'La confianza de la alianza depende demasiado de un rival.',
        ),
        q(
          'Ask the three leaders to design their own agreement before you approve it.',
          'Pides a los tres líderes que diseñen su propio acuerdo antes de aprobarlo.',
          'Encourages ownership and mutual recognition.',
          'Promueve la responsabilidad propia y el reconocimiento mutuo.',
          'The convoy waits while rivalry is negotiated.',
          'El convoy espera mientras se negocia la rivalidad.',
        ),
        q(
          'Keep command with the chamberlain and use the ward leaders only as technical advisers.',
          'Mantienes el mando en el chambelán y usas a los líderes solo como asesores técnicos.',
          'Avoids rewarding any rival faction.',
          'Evita premiar a una facción rival.',
          'Local expertise receives little authority to coordinate.',
          'La experiencia local recibe poca autoridad para coordinar.',
        ),
      ],
    },
    {
      title: b('The Border Message', 'El mensaje de la frontera'),
      narrative: b(
        'A rain-soaked courier reports that a northern bridge has failed. The river plan can continue only if wagons are rerouted before dusk, but no route has been inspected in weeks.',
        'Un mensajero empapado informa que un puente del norte ha cedido. El plan del río solo puede continuar si las carretas cambian de ruta antes del anochecer, pero ningún camino ha sido inspeccionado en semanas.',
      ),
      purpose: b(
        'Force the council plan to meet changed conditions without branching the story.',
        'Forzar al plan del consejo a enfrentar condiciones cambiantes sin ramificar la historia.',
      ),
      psychology: b(
        'Separate organized preparation from willingness to revise strategy.',
        'Separar la preparación organizada de la disposición a revisar la estrategia.',
      ),
      primary: ['structure', 'adaptability'],
      facets: ['planning', 'strategy_revision'],
      contexts: ['time_pressure', 'change'],
      pressure: true,
      visual: b(
        'A soaked courier beside a broken bridge model, wagon markers and three unmarked route cords across a relief map.',
        'Un mensajero empapado junto a una maqueta de puente roto, fichas de carretas y tres cuerdas de ruta sin marcas sobre un mapa en relieve.',
      ),
      continuity: b(
        'The water convoy still reaches the capital in the next act; only the reasoning about rerouting is measured.',
        'El convoy de agua llega a la capital en el acto siguiente; solo se mide el razonamiento sobre el cambio de ruta.',
      ),
      choices: [
        q(
          'Rebuild the convoy sequence around the best current route and set two review points before dusk.',
          'Reorganizas la secuencia del convoy alrededor de la mejor ruta actual y fijas dos puntos de revisión antes del anochecer.',
          'Updates the plan while preserving checkpoints.',
          'Actualiza el plan y conserva puntos de control.',
          'Consumes scarce time before movement begins.',
          'Consume tiempo escaso antes de iniciar el movimiento.',
        ),
        q(
          'Keep the convoy schedule but empower scouts to redirect each wagon when they meet new evidence.',
          'Mantienes el horario del convoy, pero autorizas a los exploradores a redirigir cada carreta cuando encuentren nueva evidencia.',
          'Allows rapid local adaptation.',
          'Permite una adaptación local rápida.',
          'The convoy may fragment without a shared sequence.',
          'El convoy puede fragmentarse sin una secuencia compartida.',
        ),
        q(
          'Delay departure until one route is fully inspected and documented.',
          'Retrasas la partida hasta que una ruta esté completamente inspeccionada y documentada.',
          'Reduces avoidable disorder and route uncertainty.',
          'Reduce el desorden evitable y la incertidumbre de la ruta.',
          'The capital receives water later.',
          'La capital recibe el agua más tarde.',
        ),
        q(
          'Hold to the original plan and repair the northern bridge when the convoy arrives.',
          'Mantienes el plan original y reparas el puente del norte cuando llegue el convoy.',
          'Preserves a known sequence and destination.',
          'Conserva una secuencia y un destino conocidos.',
          'Commits resources to a condition that may be worse than reported.',
          'Compromete recursos con una situación que puede ser peor de lo informado.',
        ),
      ],
    },
    {
      title: b('The Guild at the River Gate', 'El gremio en la compuerta'),
      narrative: b(
        'The barge guild controls the only working gate and offers immediate passage if its families receive priority. Refusing may delay every province; accepting will be seen from the crowded quay.',
        'El gremio de barcazas controla la única compuerta activa y ofrece paso inmediato si sus familias reciben prioridad. Rechazar puede demorar a todas las provincias; aceptar será visto desde el muelle lleno.',
      ),
      purpose: b(
        'Turn alliance into a visible negotiation with legitimate collective costs.',
        'Convertir la alianza en una negociación visible con costos colectivos legítimos.',
      ),
      psychology: b(
        'Observe coalition building and persuasion under social exposure.',
        'Observar la construcción de alianzas y la persuasión bajo exposición social.',
      ),
      primary: ['empathy_cooperation', 'social_confidence'],
      facets: ['coalition_building', 'persuasion_attempt'],
      contexts: ['negotiation', 'public_visibility'],
      visual: b(
        'A crowded stone quay, a massive wooden river gate, guild families and council delegates facing one another, symbolic flags only.',
        'Un muelle de piedra lleno, una enorme compuerta de madera, familias del gremio y delegados frente a frente, solo banderas simbólicas.',
      ),
      continuity: b(
        'The gate opens by the end of the scene in every path; the negotiated reasoning becomes later evidence.',
        'La compuerta se abre al final de la escena en todos los recorridos; el razonamiento negociado se convierte en evidencia posterior.',
      ),
      choices: [
        q(
          'Address the quay, propose limited family priority, and bind the guild to a public delivery schedule.',
          'Te diriges al muelle, propones prioridad limitada para las familias y comprometes al gremio con un horario público de entregas.',
          'Builds an explicit coalition and explains it openly.',
          'Construye una alianza explícita y la explica abiertamente.',
          'Makes you answer publicly for unequal access.',
          'Te hace responder públicamente por un acceso desigual.',
        ),
        q(
          'Negotiate privately with guild elders, including safeguards for the smallest province.',
          'Negocias en privado con los mayores del gremio e incluyes garantías para la provincia más pequeña.',
          'Protects vulnerable interests within a workable bargain.',
          'Protege intereses vulnerables dentro de un acuerdo viable.',
          'The public may mistrust an unseen negotiation.',
          'El público puede desconfiar de una negociación invisible.',
        ),
        q(
          'Ask the crowd to support equal passage and challenge the guild to defend its demand openly.',
          'Pides a la multitud que apoye el paso igualitario y desafías al gremio a defender su demanda en público.',
          'Uses visible persuasion against preferential access.',
          'Usa persuasión visible contra el acceso preferente.',
          'May weaken the relationship needed to operate the gate.',
          'Puede debilitar la relación necesaria para operar la compuerta.',
        ),
        q(
          'Accept the guild’s terms without ceremony so the convoy can move immediately.',
          'Aceptas las condiciones del gremio sin ceremonia para que el convoy avance de inmediato.',
          'Removes delay and preserves operational cooperation.',
          'Elimina la demora y conserva la cooperación operativa.',
          'Others absorb the cost without a voice or explanation.',
          'Otros absorben el costo sin voz ni explicación.',
        ),
      ],
    },
    {
      title: b('Shelter Before Winter', 'Refugio antes del invierno'),
      narrative: b(
        'Families displaced by the failed bridge fill the old armory. The western delegate offers empty estates, but only if the council lets that province choose who is admitted first.',
        'Las familias desplazadas por el puente caído llenan la antigua armería. El delegado occidental ofrece propiedades vacías, pero solo si el consejo permite que su provincia elija quién entra primero.',
      ),
      purpose: b(
        'Place care and self-directed judgment inside a constrained allocation problem.',
        'Situar el cuidado y el juicio propio dentro de un problema de asignación limitada.',
      ),
      psychology: b(
        'Observe interpersonal concern and autonomy when a useful offer carries control over selection.',
        'Observar la consideración interpersonal y la autonomía cuando una oferta útil implica control sobre la selección.',
      ),
      primary: ['empathy_cooperation', 'autonomy'],
      facets: ['interpersonal_concern', 'choice_ownership'],
      contexts: ['caregiving', 'responsibility'],
      visual: b(
        'An old armory transformed into a crowded shelter, blankets, lanterns and distant empty estates through high windows, no writing.',
        'Una antigua armería convertida en refugio lleno, mantas, faroles y propiedades vacías a lo lejos a través de ventanas altas, sin escritura.',
      ),
      continuity: b(
        'The families receive shelter in all paths and remain part of the same public responsibility debate.',
        'Las familias reciben refugio en todos los recorridos y siguen formando parte del mismo debate de responsabilidad pública.',
      ),
      choices: [
        q(
          'Accept the estates only with shared admission criteria created with displaced families.',
          'Aceptas las propiedades solo con criterios de admisión compartidos y creados con las familias desplazadas.',
          'Includes affected perspectives while preserving independent conditions.',
          'Incluye perspectivas afectadas y conserva condiciones propias.',
          'The negotiation may slow immediate placement.',
          'La negociación puede demorar la asignación inmediata.',
        ),
        q(
          'Accept now, then personally review exclusions after everyone has a roof.',
          'Aceptas ahora y luego revisas personalmente las exclusiones cuando todos tengan techo.',
          'Secures shelter while retaining later ownership of corrections.',
          'Asegura refugio y conserva responsabilidad sobre correcciones posteriores.',
          'Some families may face an unfair first decision.',
          'Algunas familias pueden enfrentar una primera decisión injusta.',
        ),
        q(
          'Let the council vote on the province’s condition after hearing testimony from the shelter.',
          'Permites que el consejo vote la condición después de escuchar testimonios del refugio.',
          'Centers affected voices and shared legitimacy.',
          'Centra las voces afectadas y la legitimidad compartida.',
          'Your own judgment may disappear inside factional votes.',
          'Tu propio juicio puede desaparecer dentro de votos facciosos.',
        ),
        q(
          'Use the western system as offered because unused shelter is better than a perfect rule arrived too late.',
          'Usas el sistema occidental tal como fue ofrecido porque un refugio imperfecto es mejor que una regla perfecta que llega tarde.',
          'Moves families quickly.',
          'Traslada a las familias con rapidez.',
          'Cedes control over who bears the unfairness.',
          'Cedes el control sobre quién carga con la injusticia.',
        ),
      ],
    },
    {
      title: b(
        'The Oath with Missing Words',
        'El juramento con palabras ausentes',
      ),
      narrative: b(
        'Two provinces present copies of an old alliance oath, but rain has erased a different passage from each. Both interpretations are plausible, and the surviving witnesses remember the ceremony differently.',
        'Dos provincias presentan copias de un antiguo juramento de alianza, pero la lluvia borró un pasaje distinto en cada una. Ambas interpretaciones son plausibles y los testigos recuerdan la ceremonia de manera diferente.',
      ),
      purpose: b(
        'Sustain ambiguity at the center of a political bargain.',
        'Mantener la ambigüedad en el centro de un acuerdo político.',
      ),
      psychology: b(
        'Observe evidence seeking without forcing false certainty and willingness to hold multiple possibilities.',
        'Observar la búsqueda de evidencia sin imponer falsa certeza y la disposición a sostener varias posibilidades.',
      ),
      primary: ['knowledge_orientation', 'openness_to_uncertainty'],
      facets: ['causal_reasoning', 'possibility_holding'],
      contexts: ['knowledge_gap', 'uncertainty'],
      visual: b(
        'Two weathered oath parchments with different blank rain-washed passages, wax symbols and elderly witnesses, no readable language.',
        'Dos pergaminos de juramento desgastados con distintos pasajes borrados por la lluvia, símbolos de cera y testigos mayores, sin lenguaje legible.',
      ),
      continuity: b(
        'No definitive original appears later; the council must act with the ambiguity it has.',
        'No aparece un original definitivo más adelante; el consejo debe actuar con la ambigüedad disponible.',
      ),
      choices: [
        q(
          'Compare material traces and testimony, then preserve both plausible readings in a temporary agreement.',
          'Comparas rastros materiales y testimonios, y conservas ambas lecturas plausibles en un acuerdo temporal.',
          'Uses evidence while acknowledging unresolved possibilities.',
          'Usa evidencia y reconoce posibilidades sin resolver.',
          'A temporary agreement may feel less authoritative.',
          'Un acuerdo temporal puede sentirse menos autoritativo.',
        ),
        q(
          'Investigate which reading better explains later actions, then choose the stronger account.',
          'Investigas qué lectura explica mejor las acciones posteriores y eliges la versión más sólida.',
          'Builds a coherent evidence-based interpretation.',
          'Construye una interpretación coherente basada en evidencia.',
          'Closes off a plausible alternative without certainty.',
          'Descarta una alternativa plausible sin certeza.',
        ),
        q(
          'Keep both readings open and ask the provinces to create a new oath without deciding the old one.',
          'Mantienes ambas lecturas abiertas y pides a las provincias crear un juramento nuevo sin decidir el anterior.',
          'Avoids manufacturing historical certainty.',
          'Evita fabricar certeza histórica.',
          'Leaves the evidence underused and the past dispute unresolved.',
          'Deja la evidencia subutilizada y el conflicto pasado sin resolver.',
        ),
        q(
          'Adopt the version recognized by the senior witness so the alliance can proceed.',
          'Adoptas la versión reconocida por el testigo de mayor rango para que la alianza avance.',
          'Provides a clear basis for immediate action.',
          'Proporciona una base clara para actuar de inmediato.',
          'Authority substitutes for investigation and ambiguity remains hidden.',
          'La autoridad sustituye la investigación y la ambigüedad queda oculta.',
        ),
      ],
    },
    {
      title: b('The Vote That Cannot Move', 'El voto que no puede avanzar'),
      narrative: b(
        'By midday the council divides evenly on the river allocation. Outside, the convoy waits under a lowering sky while every faction repeats the argument that brought it here.',
        'Al mediodía el consejo queda dividido en partes iguales sobre la distribución del río. Afuera, el convoy espera bajo un cielo cada vez más oscuro mientras cada facción repite el argumento que la trajo hasta aquí.',
      ),
      purpose: b(
        'Make stalemate operationally costly and require a bounded way forward.',
        'Volver costoso el estancamiento y exigir una salida acotada.',
      ),
      psychology: b(
        'Observe decisive coordination and structured prioritization under time pressure.',
        'Observar la coordinación decisiva y la priorización estructurada bajo presión de tiempo.',
      ),
      primary: ['leadership_initiative', 'structure'],
      facets: ['decisiveness', 'procedural_thinking'],
      contexts: ['time_pressure', 'group_coordination'],
      pressure: true,
      visual: b(
        'An evenly divided circular council, paired voting stones, darkening sky and a waiting convoy visible through the doors.',
        'Un consejo circular dividido en partes iguales, piedras de voto emparejadas, cielo oscuro y un convoy esperando tras las puertas.',
      ),
      continuity: b(
        'The council reaches one allocation before the scene ends; subsequent scenes test how it is carried, not alternate plot branches.',
        'El consejo alcanza una distribución antes de terminar la escena; las escenas siguientes prueban cómo se sostiene, no ramas narrativas alternativas.',
      ),
      choices: [
        q(
          'Define the two urgent criteria, call a final timed round, and take responsibility for the tie-break.',
          'Defines los dos criterios urgentes, convocas una ronda final cronometrada y asumes la responsabilidad del desempate.',
          'Creates a structured decision and accountable closure.',
          'Crea una decisión estructurada y un cierre responsable.',
          'Concentrates the final cost in your judgment.',
          'Concentra el costo final en tu juicio.',
        ),
        q(
          'Appoint a small cross-faction group to decide within the hour and bind the chamber to its result.',
          'Nombras un grupo pequeño entre facciones para decidir en una hora y comprometes a la cámara con su resultado.',
          'Delegates coordination with a firm deadline.',
          'Delega coordinación con un plazo firme.',
          'The selection process may shape the outcome.',
          'El proceso de selección puede moldear el resultado.',
        ),
        q(
          'Reorder the vote into separate decisions on survival needs, reserves and repair.',
          'Reordenas el voto en decisiones separadas sobre supervivencia, reservas y reparación.',
          'Reduces complexity through procedure.',
          'Reduce la complejidad mediante un procedimiento.',
          'May produce pieces that conflict when combined.',
          'Puede producir piezas que entren en conflicto al combinarse.',
        ),
        q(
          'Extend debate until one faction changes voluntarily.',
          'Extiendes el debate hasta que una facción cambie voluntariamente.',
          'Protects consent and avoids imposed closure.',
          'Protege el consentimiento y evita un cierre impuesto.',
          'Delay transfers the cost to people outside the chamber.',
          'La demora transfiere el costo a quienes están fuera de la cámara.',
        ),
      ],
    },
    {
      title: b('The Envoy Who Did Not Return', 'El enviado que no regresó'),
      narrative: b(
        'The eastern envoy misses the agreed hour. A folded warning arrives instead: unknown riders closed the valley road, and the council must decide whether to revise the pact without one province present.',
        'El enviado oriental no llega a la hora acordada. En su lugar aparece una advertencia doblada: jinetes desconocidos cerraron el camino del valle y el consejo debe decidir si revisa el pacto sin una provincia presente.',
      ),
      purpose: b(
        'Test responsibility when representation and conditions change together.',
        'Poner a prueba la responsabilidad cuando cambian al mismo tiempo la representación y las condiciones.',
      ),
      psychology: b(
        'Observe self-directed ownership and evidence-based strategy revision.',
        'Observar la responsabilidad autodirigida y la revisión de estrategia basada en evidencia.',
      ),
      primary: ['autonomy', 'adaptability'],
      facets: ['choice_ownership', 'feedback_learning'],
      contexts: ['responsibility', 'change'],
      visual: b(
        'An empty eastern chair, a folded warning marked only by a black feather symbol, and a valley route blocked by dark rider tokens.',
        'Un asiento oriental vacío, una advertencia doblada marcada solo con una pluma negra y una ruta bloqueada por fichas de jinetes oscuros.',
      ),
      continuity: b(
        'The eastern province remains represented by its earlier stated needs; no rescue side quest begins.',
        'La provincia oriental sigue representada por sus necesidades ya expresadas; no comienza una misión secundaria de rescate.',
      ),
      choices: [
        q(
          'Revise only the affected provisions, record your reasons, and accept responsibility for reopening them later.',
          'Revisas solo las cláusulas afectadas, registras tus razones y asumes reabrirlas más adelante.',
          'Adapts to evidence with explicit ownership.',
          'Se adapta a la evidencia con responsabilidad explícita.',
          'The absent province may still reject the interim choice.',
          'La provincia ausente aún puede rechazar la decisión provisional.',
        ),
        q(
          'Keep the pact intact but create a contingency you can activate if the warning is confirmed.',
          'Mantienes el pacto intacto, pero creas una contingencia que podrás activar si se confirma la advertencia.',
          'Preserves commitment while preparing to adapt.',
          'Conserva el compromiso mientras prepara una adaptación.',
          'Action may lag behind a real change.',
          'La acción puede quedar detrás de un cambio real.',
        ),
        q(
          'Ask the remaining council to revise the pact collectively and share accountability.',
          'Pides al consejo restante revisar el pacto de forma colectiva y compartir la responsabilidad.',
          'Uses the group to adjust to changed conditions.',
          'Usa al grupo para ajustarse a condiciones cambiantes.',
          'Your judgment may be overtaken by factional interests.',
          'Tu juicio puede quedar desplazado por intereses facciosos.',
        ),
        q(
          'Postpone revision until the envoy returns or sends verifiable instructions.',
          'Postergas la revisión hasta que el enviado regrese o envíe instrucciones verificables.',
          'Protects representation and avoids acting on rumor.',
          'Protege la representación y evita actuar por rumores.',
          'The current plan may fail while certainty is sought.',
          'El plan actual puede fallar mientras se busca certeza.',
        ),
      ],
    },
    {
      title: b('Bells in the Lower Quarter', 'Campanas en el barrio bajo'),
      narrative: b(
        'Alarm bells rise from the lower quarter as news of the allocation spreads. The crowd has not become violent, but exhausted guards ask whether to close the square before fear turns into panic.',
        'Las campanas de alarma suben desde el barrio bajo cuando se difunde la distribución. La multitud no se ha vuelto violenta, pero los guardias agotados preguntan si deben cerrar la plaza antes de que el miedo se convierta en pánico.',
      ),
      purpose: b(
        'Move the consequence of council language into the public realm.',
        'Trasladar la consecuencia del lenguaje del consejo al espacio público.',
      ),
      psychology: b(
        'Observe composure and sustained responsibility when tension becomes collective.',
        'Observar la calma y la responsabilidad sostenida cuando la tensión se vuelve colectiva.',
      ),
      primary: ['emotional_regulation', 'persistence'],
      facets: ['affect_tolerance', 'goal_commitment'],
      contexts: ['social_risk', 'responsibility'],
      pressure: true,
      visual: b(
        'A lower city square at twilight, warning bells, an anxious but nonviolent crowd and visibly tired guards holding open space.',
        'Una plaza baja al anochecer, campanas de alarma, una multitud ansiosa pero no violenta y guardias cansados que mantienen el espacio abierto.',
      ),
      continuity: b(
        'The protagonist returns to the same council chamber after addressing the square; no riot or battle occurs.',
        'El protagonista regresa a la misma cámara después de atender la plaza; no ocurre ningún disturbio ni batalla.',
      ),
      choices: [
        q(
          'Go to the square, regulate the pace of questions, and stay until the allocation and its limits are understood.',
          'Vas a la plaza, regulas el ritmo de las preguntas y permaneces hasta que se comprendan la distribución y sus límites.',
          'Sustains the difficult task while containing emotional escalation.',
          'Sostiene la tarea difícil y contiene la escalada emocional.',
          'Requires endurance and exposes you to prolonged anger.',
          'Exige resistencia y te expone a un enojo prolongado.',
        ),
        q(
          'Send a calm public explanation now and schedule direct questions after the convoy departs.',
          'Envías ahora una explicación serena y programas preguntas directas después de que parta el convoy.',
          'Preserves function and protects the urgent schedule.',
          'Conserva el funcionamiento y protege el horario urgente.',
          'Distance may be interpreted as avoidance.',
          'La distancia puede interpretarse como evasión.',
        ),
        q(
          'Keep the square open and let local leaders hold the conversation while you finish the council work.',
          'Mantienes abierta la plaza y permites que líderes locales sostengan la conversación mientras terminas el trabajo del consejo.',
          'Maintains continuity without abandoning the objective.',
          'Mantiene continuidad sin abandonar el objetivo.',
          'Relies on others to absorb the immediate tension.',
          'Depende de otros para absorber la tensión inmediata.',
        ),
        q(
          'Close the square temporarily and wait for fear to settle before explaining the decision.',
          'Cierras la plaza temporalmente y esperas que el miedo disminuya antes de explicar la decisión.',
          'Reduces immediate stimulation and protects tired guards.',
          'Reduce el estímulo inmediato y protege a los guardias cansados.',
          'Silence can intensify suspicion and delay accountability.',
          'El silencio puede intensificar la sospecha y demorar la responsabilidad.',
        ),
      ],
    },
    {
      title: b('The Chamber in Darkness', 'La cámara a oscuras'),
      narrative: b(
        'A storm extinguishes the chamber lamps as a second message arrives: one reservoir wall is failing. Delegates speak over one another while the brass seal disappears beneath scattered maps.',
        'Una tormenta apaga las lámparas de la cámara cuando llega un segundo mensaje: el muro de un reservorio está cediendo. Los delegados hablan unos sobre otros mientras el sello de bronce desaparece bajo los mapas.',
      ),
      purpose: b(
        'Bring the central crisis to a bounded, high-pressure coordination point.',
        'Llevar la crisis central a un punto acotado de coordinación bajo alta presión.',
      ),
      psychology: b(
        'Observe leadership initiative with emotional functioning during sudden overload.',
        'Observar iniciativa de liderazgo con funcionamiento emocional durante una sobrecarga repentina.',
      ),
      primary: ['leadership_initiative', 'emotional_regulation'],
      facets: ['mobilization', 'impulse_regulation'],
      contexts: ['time_pressure', 'responsibility'],
      pressure: true,
      visual: b(
        'A dark council chamber lit by lightning and one fallen lamp, scattered relief maps, delegates in urgent motion and the brass seal partly visible.',
        'Una cámara oscura iluminada por relámpagos y una lámpara caída, mapas en relieve dispersos, delegados en movimiento urgente y el sello de bronce parcialmente visible.',
      ),
      continuity: b(
        'The reservoir is stabilized off-screen by the same available crews; the choice concerns how the council mobilizes them.',
        'El reservorio es estabilizado fuera de escena por los mismos equipos disponibles; la elección se refiere a cómo el consejo los moviliza.',
      ),
      choices: [
        q(
          'Restore one speaking order, assign immediate roles, and state what remains unknown before anyone moves.',
          'Restableces un orden de palabra, asignas funciones inmediatas y declaras lo que aún no se sabe antes de que alguien se mueva.',
          'Mobilizes coordinated action without denying uncertainty.',
          'Moviliza acción coordinada sin negar la incertidumbre.',
          'A brief pause may feel costly in an emergency.',
          'Una breve pausa puede sentirse costosa en una emergencia.',
        ),
        q(
          'Issue the two essential orders first, then step aside to steady yourself while delegates execute them.',
          'Das primero las dos órdenes esenciales y luego te apartas para recuperar la calma mientras los delegados las ejecutan.',
          'Creates movement and protects continued function.',
          'Genera movimiento y protege el funcionamiento continuo.',
          'Later coordination depends on others interpreting sparse direction.',
          'La coordinación posterior depende de cómo otros interpreten una dirección escasa.',
        ),
        q(
          'Slow the room, ask the most composed delegate to coordinate, and remain available for decisions.',
          'Desaceleras la sala, pides al delegado más sereno que coordine y quedas disponible para decidir.',
          'Protects emotional function through deliberate delegation.',
          'Protege la función emocional mediante delegación deliberada.',
          'Your visible initiative becomes less direct.',
          'Tu iniciativa visible se vuelve menos directa.',
        ),
        q(
          'Wait for the engineers’ complete report before directing the council.',
          'Esperas el informe completo de los ingenieros antes de dirigir al consejo.',
          'Avoids sending people on assumptions.',
          'Evita movilizar personas sobre supuestos.',
          'The room remains uncoordinated during a narrowing window.',
          'La sala sigue sin coordinación durante un margen que se reduce.',
        ),
      ],
    },
    {
      title: b('Three Carts, Five Needs', 'Tres carretas, cinco necesidades'),
      narrative: b(
        'Only three carts remain before the reservoir road closes. Grain, medicine, timber, engineers and evacuees all have a credible claim, and every choice leaves something behind.',
        'Solo quedan tres carretas antes de que cierre el camino al reservorio. Grano, medicinas, madera, ingenieros y evacuados tienen reclamos legítimos, y toda elección deja algo atrás.',
      ),
      purpose: b(
        'Create an unavoidable allocation trade-off with no morally perfect answer.',
        'Crear un intercambio de asignación inevitable sin una respuesta moralmente perfecta.',
      ),
      psychology: b(
        'Observe structured prioritization alongside interpersonal concern.',
        'Observar la priorización estructurada junto con la consideración interpersonal.',
      ),
      primary: ['structure', 'empathy_cooperation'],
      facets: ['prioritization', 'prosocial_response'],
      contexts: ['resource_scarcity', 'moral_tradeoff'],
      pressure: true,
      visual: b(
        'Three wooden carts in a rain-dark courtyard facing five groups represented by grain, medicine, timber, engineers and families, no labels.',
        'Tres carretas de madera en un patio lluvioso frente a cinco grupos representados por grano, medicinas, madera, ingenieros y familias, sin etiquetas.',
      ),
      continuity: b(
        'All five needs remain visible in the final council review; the Journey does not imply one was erased.',
        'Las cinco necesidades siguen visibles en la revisión final; el Journey no implica que una haya desaparecido.',
      ),
      choices: [
        q(
          'Rank immediate loss, assign three carts, and create a named next action for each need left behind.',
          'Ordenas las pérdidas inmediatas, asignas tres carretas y creas una próxima acción concreta para cada necesidad que queda atrás.',
          'Combines clear priority with care for deferred needs.',
          'Combina prioridad clara con cuidado por las necesidades postergadas.',
          'Makes unequal sacrifice explicit and attributable.',
          'Hace explícito y atribuible el sacrificio desigual.',
        ),
        q(
          'Ask affected groups which two loads can be combined, then choose the third by urgency.',
          'Preguntas a los grupos afectados qué dos cargas pueden combinarse y eliges la tercera por urgencia.',
          'Invites cooperative solutions.',
          'Invita a soluciones cooperativas.',
          'Negotiation consumes the closing window.',
          'La negociación consume el margen disponible.',
        ),
        q(
          'Use survival duration and repair impact as fixed criteria for all five claims.',
          'Usas duración de supervivencia e impacto de reparación como criterios fijos para los cinco reclamos.',
          'Produces a consistent and explainable allocation.',
          'Produce una asignación consistente y explicable.',
          'Human needs that resist measurement may be undervalued.',
          'Las necesidades humanas difíciles de medir pueden quedar subvaloradas.',
        ),
        q(
          'Send the first three ready loads to avoid losing any cart to delay.',
          'Envías las primeras tres cargas listas para evitar perder carretas por demora.',
          'Maximizes immediate movement.',
          'Maximiza el movimiento inmediato.',
          'Readiness, rather than need, decides who bears the cost.',
          'La preparación, y no la necesidad, decide quién carga con el costo.',
        ),
      ],
    },
    {
      title: b('Dissent at Your Side', 'Disenso a tu lado'),
      narrative: b(
        'Mara, the clerk who recovered the missing seal, quietly tells you the council’s allocation is lawful but wrong. In minutes you must present it to people who will recognize hesitation.',
        'Mara, la escriba que recuperó el sello perdido, te dice en voz baja que la distribución del consejo es legal pero equivocada. En minutos debes presentarla ante personas que reconocerán cualquier vacilación.',
      ),
      purpose: b(
        'Put personal judgment and visible disagreement beside institutional duty.',
        'Situar el juicio personal y el desacuerdo visible junto al deber institucional.',
      ),
      psychology: b(
        'Observe resistance to social pressure and willingness to express disagreement.',
        'Observar la resistencia a la presión social y la disposición a expresar desacuerdo.',
      ),
      primary: ['autonomy', 'social_confidence'],
      facets: ['social_pressure_resistance', 'assertive_expression'],
      contexts: ['authority', 'social_risk'],
      visual: b(
        'A side corridor outside the council, a clerk holding the recovered brass seal while torchlit petitioners wait beyond an arch.',
        'Un corredor lateral fuera del consejo, una escriba sostiene el sello recuperado mientras peticionarios esperan bajo antorchas tras un arco.',
      ),
      continuity: b(
        'The adopted allocation remains the same plot event; the decision changes how the protagonist owns and communicates it.',
        'La distribución adoptada sigue siendo el mismo evento narrativo; la decisión cambia cómo el protagonista la asume y comunica.',
      ),
      choices: [
        q(
          'Return to the chamber, state your objection clearly, and ask for one final bounded revision.',
          'Regresas a la cámara, declaras tu objeción con claridad y pides una última revisión acotada.',
          'Owns independent disagreement in a visible forum.',
          'Asume un desacuerdo independiente en un foro visible.',
          'May reopen conflict at the final hour.',
          'Puede reabrir el conflicto en la hora final.',
        ),
        q(
          'Record your objection privately, then alter the implementation where your authority allows.',
          'Registras tu objeción en privado y luego ajustas la implementación donde tu autoridad lo permite.',
          'Preserves personal judgment with less public rupture.',
          'Conserva el juicio personal con menor ruptura pública.',
          'Others cannot evaluate the hidden disagreement.',
          'Otros no pueden evaluar el desacuerdo oculto.',
        ),
        q(
          'Present the decision faithfully but say publicly which cost you believe the council underestimated.',
          'Presentas la decisión con fidelidad, pero dices en público qué costo crees que el consejo subestimó.',
          'Uses visible candor while honoring the collective result.',
          'Usa franqueza visible y honra el resultado colectivo.',
          'Your autonomy stops short of changing the decision.',
          'Tu autonomía no llega a cambiar la decisión.',
        ),
        q(
          'Present the allocation as the council’s unified position and reserve doubt for the later review.',
          'Presentas la distribución como posición unificada del consejo y reservas la duda para la revisión posterior.',
          'Protects institutional coherence.',
          'Protege la coherencia institucional.',
          'Social agreement overrides an immediate personal warning.',
          'El acuerdo social desplaza una advertencia personal inmediata.',
        ),
      ],
    },
    {
      title: b('The Decree Without a Crown', 'El decreto sin corona'),
      narrative: b(
        'The regent still has not arrived. The chamberlain says the plan needs one seal to become binding and places the brass medallion in your hand while the delegates watch in silence.',
        'El regente aún no llega. El chambelán dice que el plan necesita un sello para ser vinculante y coloca el medallón de bronce en tu mano mientras los delegados observan en silencio.',
      ),
      purpose: b(
        'Resolve the authority question introduced by the empty seat.',
        'Resolver la pregunta de autoridad introducida por el asiento vacío.',
      ),
      psychology: b(
        'Observe responsibility assumption and independent ownership when authority is temporary and imperfect.',
        'Observar la asunción de responsabilidad y la autonomía cuando la autoridad es temporal e imperfecta.',
      ),
      primary: ['leadership_initiative', 'autonomy'],
      facets: ['responsibility_assumption', 'choice_ownership'],
      contexts: ['authority', 'responsibility'],
      visual: b(
        'A hand holding the familiar brass council seal above a completed relief map, empty regent chair in the background, no writing.',
        'Una mano sostiene el conocido sello del consejo sobre un mapa en relieve completo, con el asiento vacío al fondo y sin escritura.',
      ),
      continuity: b(
        'The same plan is enacted in all paths; the choice records how responsibility is assumed and bounded.',
        'El mismo plan se ejecuta en todos los recorridos; la elección registra cómo se asume y limita la responsabilidad.',
      ),
      choices: [
        q(
          'Seal the decree, state the temporary limits of your authority, and accept review when the regent returns.',
          'Sellas el decreto, declaras los límites temporales de tu autoridad y aceptas una revisión cuando vuelva el regente.',
          'Creates accountable movement with independent ownership.',
          'Genera movimiento responsable con autonomía.',
          'You carry responsibility for a decision made without full mandate.',
          'Cargas con la responsabilidad de una decisión sin mandato completo.',
        ),
        q(
          'Seal only the emergency provisions and leave long-term clauses unsigned.',
          'Sellas solo las disposiciones de emergencia y dejas sin firma las cláusulas de largo plazo.',
          'Acts independently within a narrower boundary.',
          'Actúa con autonomía dentro de un límite más estrecho.',
          'The incomplete decree may weaken coordination later.',
          'El decreto incompleto puede debilitar la coordinación posterior.',
        ),
        q(
          'Ask every delegate to touch the seal before you press it on their collective behalf.',
          'Pides a cada delegado tocar el sello antes de presionarlo en nombre del colectivo.',
          'Shares legitimacy and responsibility visibly.',
          'Comparte legitimidad y responsabilidad de forma visible.',
          'Your own ownership becomes intertwined with consensus.',
          'Tu responsabilidad queda entrelazada con el consenso.',
        ),
        q(
          'Have the chamberlain seal it under established emergency custom.',
          'Pides al chambelán que lo selle según la costumbre de emergencia.',
          'Preserves continuity with recognized office.',
          'Conserva continuidad con un cargo reconocido.',
          'Avoids personally owning the decisive act.',
          'Evita asumir personalmente el acto decisivo.',
        ),
      ],
    },
    {
      title: b('The Square Hears the Cost', 'La plaza escucha el costo'),
      narrative: b(
        'At sunset the square gathers to hear what was decided. Those receiving less stand beside those receiving first relief, and neither silence nor ceremony can hide the unequal cost.',
        'Al atardecer la plaza se reúne para escuchar lo decidido. Quienes reciben menos están junto a quienes reciben ayuda primero, y ni el silencio ni la ceremonia pueden ocultar el costo desigual.',
      ),
      purpose: b(
        'Make public explanation part of stewardship rather than a victory speech.',
        'Hacer de la explicación pública una parte del cuidado y no un discurso de victoria.',
      ),
      psychology: b(
        'Observe interpersonal visibility and perspective taking during accountability.',
        'Observar la visibilidad interpersonal y la toma de perspectiva durante la rendición de cuentas.',
      ),
      primary: ['social_confidence', 'empathy_cooperation'],
      facets: ['interpersonal_visibility', 'perspective_taking'],
      contexts: ['public_visibility', 'moral_tradeoff'],
      visual: b(
        'A broad city square at sunset, mixed groups around a low stone platform, water carts in the distance, symbolic banners without text.',
        'Una gran plaza al atardecer, grupos diversos alrededor de una plataforma baja y carretas de agua a lo lejos, estandartes simbólicos sin texto.',
      ),
      continuity: b(
        'The square receives the same core decision; only the communication strategy differs.',
        'La plaza recibe la misma decisión central; solo cambia la estrategia de comunicación.',
      ),
      choices: [
        q(
          'Explain the decision yourself, name who bears each cost, and invite two affected voices to answer you.',
          'Explicas la decisión, nombras quién carga cada costo e invitas a dos voces afectadas a responderte.',
          'Combines visible accountability with perspective taking.',
          'Combina rendición de cuentas visible con toma de perspectiva.',
          'Opens the decision to direct criticism before implementation.',
          'Abre la decisión a críticas directas antes de implementarla.',
        ),
        q(
          'Walk among affected families first, then deliver a shorter explanation based on what you heard.',
          'Caminas primero entre las familias afectadas y luego das una explicación breve basada en lo escuchado.',
          'Centers lived consequences.',
          'Centra las consecuencias vividas.',
          'Private listening may leave the wider square uncertain at first.',
          'La escucha privada puede dejar incierta a la plaza al principio.',
        ),
        q(
          'Present the reasons and limits clearly, then ask local delegates to hold separate listening circles.',
          'Presentas con claridad las razones y límites, y luego pides a delegados locales sostener círculos de escucha.',
          'Uses public clarity and distributed dialogue.',
          'Usa claridad pública y diálogo distribuido.',
          'You do not hear every response directly.',
          'No escuchas cada respuesta de forma directa.',
        ),
        q(
          'Publish the allocation through heralds and remain in the chamber to supervise execution.',
          'Difundes la distribución mediante heraldos y permaneces en la cámara para supervisar la ejecución.',
          'Protects operational attention.',
          'Protege la atención operativa.',
          'Reduces mutual understanding and personal visibility.',
          'Reduce la comprensión mutua y la visibilidad personal.',
        ),
      ],
    },
    {
      title: b('The First Review', 'La primera revisión'),
      narrative: b(
        'Before midnight, reports show the plan saved the failing reservoir but left one district waiting longer than expected. The council can defend its success, reopen its reasoning or preserve uncertainty for the next review.',
        'Antes de la medianoche, los informes muestran que el plan salvó el reservorio, pero dejó a un distrito esperando más de lo previsto. El consejo puede defender su éxito, revisar su razonamiento o conservar la incertidumbre para la próxima evaluación.',
      ),
      purpose: b(
        'Close the Journey with consequences, learning and unfinished stewardship.',
        'Cerrar el Journey con consecuencias, aprendizaje y una responsabilidad que continúa.',
      ),
      psychology: b(
        'Observe sustained engagement and tolerance for an outcome that is both useful and incomplete.',
        'Observar el compromiso sostenido y la tolerancia ante un resultado útil pero incompleto.',
      ),
      primary: ['persistence', 'openness_to_uncertainty'],
      facets: ['setback_recovery', 'incomplete_answer_tolerance'],
      contexts: ['loss', 'uncertainty'],
      visual: b(
        'The council chamber near midnight, first relief reports represented by tokens, a saved reservoir model and one district marker still waiting, no words.',
        'La cámara cerca de medianoche, informes representados por fichas, una maqueta del reservorio salvado y una ficha de distrito aún en espera, sin palabras.',
      ),
      continuity: b(
        'The brass seal is returned beside the empty seat, completing the same linear council day for every traveler.',
        'El sello de bronce vuelve junto al asiento vacío y completa el mismo día lineal de consejo para cada viajero.',
      ),
      choices: [
        q(
          'Stay for a second review, examine the delayed district without erasing what worked, and define the next correction.',
          'Permaneces para una segunda revisión, examinas el distrito demorado sin borrar lo que funcionó y defines la próxima corrección.',
          'Sustains effort while accepting an incomplete outcome.',
          'Sostiene el esfuerzo y acepta un resultado incompleto.',
          'Extends responsibility beyond the emotional relief of success.',
          'Extiende la responsabilidad más allá del alivio emocional del éxito.',
        ),
        q(
          'Record the delay as a known failure, continue the plan tonight, and set a fixed dawn review.',
          'Registras la demora como una falla conocida, continúas el plan esta noche y fijas una revisión al amanecer.',
          'Preserves momentum with a bounded unknown.',
          'Conserva el impulso con una incógnita acotada.',
          'The district waits through the night.',
          'El distrito espera durante la noche.',
        ),
        q(
          'Reopen the plan now and let the council hold several explanations until a better correction appears.',
          'Reabres el plan ahora y permites que el consejo sostenga varias explicaciones hasta que aparezca una mejor corrección.',
          'Keeps possibilities alive and treats the setback seriously.',
          'Mantiene posibilidades abiertas y toma en serio el contratiempo.',
          'May interrupt a plan that is already delivering relief.',
          'Puede interrumpir un plan que ya está entregando ayuda.',
        ),
        q(
          'Conclude that the central objective was met and leave the delayed district to the next council.',
          'Concluyes que el objetivo central se cumplió y dejas el distrito demorado al próximo consejo.',
          'Ends a demanding cycle and preserves finite effort.',
          'Cierra un ciclo exigente y conserva esfuerzo limitado.',
          'Stops before the remaining consequence is understood.',
          'Se detiene antes de comprender la consecuencia restante.',
        ),
      ],
    },
  ],
});
