import { archetypes } from '../registry/archetypes.js';
import { dimensions } from '../registry/dimensions.js';
import {
  deepFreeze,
  journeyContentSchema,
  type ScoreEffects,
} from '../types.js';

type DraftChoice = { text: string; scores: Partial<ScoreEffects> };

const option = (
  text: string,
  archetypes: Record<string, number>,
  motivations: Record<string, number>,
  decision_styles: Record<string, number>,
  traits: Record<string, number> = {},
  shadow: Record<string, number> = {},
): DraftChoice => ({
  text,
  scores: { archetypes, motivations, decision_styles, traits, shadow },
});

const scene = (
  order: number,
  act: number,
  title: string,
  narrative: string,
  image_prompt: string,
  choices: DraftChoice[],
  is_pressure = false,
) => ({
  id: `scene_${String(order).padStart(2, '0')}`,
  order,
  act,
  title,
  narrative,
  image_prompt,
  is_pressure,
  choices: choices.map((choice, i) => ({
    ...choice,
    id: `scene_${String(order).padStart(2, '0')}_choice_${'abcd'[i]}`,
  })),
});

export const journeyV1 = deepFreeze(
  journeyContentSchema.parse({
    id: 'archetype-journey',
    slug: 'the-unwritten-road',
    title: 'The Unwritten Road',
    journey_version: '1.1',
    scoring_version: '1.1',
    archetypes,
    dimensions,
    scenes: [
      scene(
        1,
        1,
        'The Ink Is Still Fresh',
        'You wake with the last note of a forgotten melody still trembling in your chest. At your door lies a letter that bears no seal and names no sender. Inside, a torn map shows a road, an abandoned travelers’ station and a lighthouse beyond the coast. The ink is still wet. From the empty station, a bell begins to ring. You do not know who chose you, how the letter arrived or where the road will truly lead. You only know that the first response is yours.',
        'A solitary traveler holding an unsealed letter and torn map at dawn, an abandoned stone waystation visible beyond misty fields, its bell moving despite the empty road, a distant lighthouse drawn on the map.',
        [
          option('Leave at once and follow the bell before uncertainty can turn into hesitation.', { explorer: 2, hero: 2 }, { freedom: 2 }, { impulsive: 1, intuitive: 1 }, { curiosity: 1, persistence: 1 }),
          option('Inspect the paper, the doorway and the ground outside for any detail the sender may have left behind.', { sage: 2, ruler: 2 }, { knowledge: 2 }, { rational: 2, strategic: 1 }, { curiosity: 1 }),
          option('Wait for the bell to sound again and listen for a pattern before deciding when to move.', { magician: 2, innocent: 2 }, { knowledge: 1, protection: 1 }, { intuitive: 2 }, { curiosity: 1, social_trust: 1 }),
          option('Pack water, food and bandages, preparing for needs the map cannot predict.', { caregiver: 2, hero: 2 }, { protection: 2 }, { protective: 2, strategic: 1 }, { persistence: 1 }),
        ],
      ),
      scene(
        2,
        1,
        'The Merchant Who Recognized the Letter',
        'The map leads through a night market beside the abandoned station. Lanterns are being lowered and the final stalls are closing when a merchant sees your letter and forgets his weariness. He tells you that, at sunset, a masked flutist played beneath the full moon and placed similar letters into the hands of a chosen few. Each map points toward the Lighthouse of Vigil, yet no one knows what waits there. The merchant offers no bargain. He only gives you time for one honest question before you continue.',
        'A closing medieval night market beside an abandoned travelers’ station, lanterns dimming, a curious merchant recognizing the letter in the traveler’s hands, traces of a masked flutist’s ceremony under a full moon.',
        [
          option('Ask about the distance, the terrain and the dangers between the market and the lighthouse.', { explorer: 2, ruler: 2 }, { freedom: 1, protection: 1 }, { strategic: 2 }, { autonomy: 1 }),
          option('Ask who the flutist was and what might have guided his choice of travelers.', { sage: 2, magician: 2 }, { knowledge: 2 }, { rational: 1, intuitive: 1 }, { curiosity: 2 }),
          option('Ask what the merchant felt while the melody was playing and why he still remembers it.', { lover: 2, caregiver: 2 }, { connection: 2 }, { protective: 1, intuitive: 1 }, { empathy: 2 }),
          option('Accept that no explanation is complete and ask what hope draws people toward the lighthouse.', { innocent: 2, jester: 2 }, { connection: 1, freedom: 1 }, { intuitive: 2 }, { social_trust: 2 }),
        ],
      ),
      scene(
        3,
        2,
        'The Broken Bridge',
        'Beyond the station, the road narrows over a gorge. Part of the old bridge has collapsed, leaving wet boards, a frayed guide rope and one open span above the river. Other letter-bearers have reached the same obstacle. No alternate road appears on any map, and the storm behind you is getting closer. The bridge must be crossed, but the way you meet the danger is still your own.',
        'A broken wooden bridge spanning a deep river gorge in approaching rain, several travelers studying the same damaged crossing, wet ropes and splintered boards, no alternate route visible.',
        [
          option('Fasten the rope around yourself and test the strongest-looking section with the first step.', { hero: 2, explorer: 2 }, { protection: 1, freedom: 1 }, { impulsive: 2 }, { risk_tolerance: 2 }, { self_sacrifice: 1 }),
          option('Examine the supports and mark the boards most likely to carry everyone safely.', { sage: 2, ruler: 2 }, { knowledge: 1, protection: 1 }, { rational: 2, strategic: 1 }, { persistence: 1 }),
          option('Use loose timber and cord to reinforce the open span before anyone crosses.', { creator: 2, magician: 2 }, { creation: 2 }, { strategic: 1, intuitive: 1 }, { curiosity: 1 }),
          option('Watch the rhythm of the wind and choose the brief calm in which movement feels possible.', { jester: 2, explorer: 2 }, { freedom: 2 }, { intuitive: 2 }, { risk_tolerance: 1, autonomy: 1 }, { avoidance: 1 }),
        ],
        true,
      ),
      scene(
        4,
        2,
        'The Storm in the Watchtower',
        'However each traveler crossed, every foot reaches the far bank. Rain overtakes the road, and the group shelters in a ruined watchtower before nightfall. Water enters through a broken window. Old route markings cover one wall, supplies are scattered across the floor and fear has made the room smaller than it is. The storm will pass on its own. What you choose is how to inhabit this waiting.',
        'Travelers sheltering from a violent storm inside a ruined stone watchtower, rain through a broken window, old route markings on the walls, scattered packs, tense faces lit by a small lantern.',
        [
          option('Organize the dry space, clear the exits and give the room a simple order.', { ruler: 2, everyman: 2 }, { power: 1, protection: 1 }, { dominant: 1, strategic: 1 }, { persistence: 1 }, { control: 1 }),
          option('Study the faded markings to understand which roads once connected this tower to the coast.', { sage: 2, explorer: 2 }, { knowledge: 2 }, { rational: 2 }, { curiosity: 2 }),
          option('Cover the broken window with cloth and timber so the shelter can protect everyone until morning.', { creator: 2, caregiver: 2 }, { creation: 1, protection: 1 }, { protective: 1, strategic: 1 }, { persistence: 1 }),
          option('Tell a story that gives the frightened travelers somewhere else to place their attention.', { lover: 2, jester: 2 }, { connection: 2 }, { intuitive: 1, protective: 1 }, { empathy: 2 }),
        ],
        true,
      ),
      scene(
        5,
        3,
        'A Stranger Beside the Fire',
        'By morning, the storm has emptied itself. The travelers separate according to pace, and you return to the road alone. At dusk, you find a woman named Mara beside a fire. Her map bears the same lighthouse, although its coast is drawn differently. She does not ask to join you, and you do not need to decide her future. For one evening, two unfinished journeys share the same light.',
        'A lone traveler meeting Mara beside a small campfire at dusk, two torn maps of the same distant lighthouse spread between them, quiet forest shelter, warm fire against cool blue night.',
        [
          option('Compare the maps carefully and identify what each one reveals that the other leaves out.', { sage: 2, magician: 2 }, { knowledge: 2 }, { rational: 1, intuitive: 1 }, { curiosity: 2 }),
          option('Ask what kept Mara moving and share the part of your own reason you have not yet spoken aloud.', { lover: 2, innocent: 2 }, { connection: 2 }, { intuitive: 1, protective: 1 }, { empathy: 2, social_trust: 1 }),
          option('Draw a clearer version of the next stretch so either traveler could understand it later.', { creator: 2, ruler: 2 }, { creation: 2 }, { strategic: 2 }, { persistence: 1 }),
          option('Turn the evening into a game of impossible stories and let laughter make room for honesty.', { jester: 2, everyman: 2 }, { connection: 2 }, { intuitive: 2 }, { social_trust: 1, empathy: 1 }),
        ],
      ),
      scene(
        6,
        3,
        'The Cart in the Mud',
        'Mara leaves at first light, following her own pace. Near midday, you reach a narrow pass where a supply cart has sunk to its axle. It carries lamp oil, blankets and food toward the coastal camp below the lighthouse. The driver and the other travelers agree on the destination but not on what to do first. The cart will continue once enough hands find a common rhythm.',
        'A supply cart carrying lamp oil, blankets and food stuck axle-deep in mud on a narrow mountain pass, travelers gathered around the wheel, the distant coast and lighthouse ahead.',
        [
          option('Name the tasks, match them to willing hands and coordinate one attempt.', { ruler: 2, everyman: 2 }, { power: 1, connection: 1 }, { dominant: 2, strategic: 1 }, { persistence: 1 }, { control: 1 }),
          option('Set a timber lever beneath the wheel and give the group something concrete to push against.', { hero: 2, creator: 2 }, { creation: 1, protection: 1 }, { impulsive: 1, strategic: 1 }, { persistence: 2 }),
          option('Turn the competing ideas into quick trials and use humor to keep failure from becoming blame.', { jester: 2, magician: 2 }, { creation: 1, connection: 1 }, { intuitive: 2 }, { curiosity: 1, empathy: 1 }),
          option('Challenge the assumption that everything must remain loaded and remove the weight that can be carried separately.', { outlaw: 2, explorer: 2 }, { freedom: 2 }, { rational: 1, dominant: 1 }, { autonomy: 2 }, { rebellion: 1 }),
        ],
        true,
      ),
      scene(
        7,
        4,
        'The Creature Beneath the Shelter',
        'The cart rolls on, and the road descends into an old cedar forest. Beneath a collapsed roadside shelter, you hear breathing too deep to be human. A young griffin is trapped by a leather strap twisted around a fallen branch. Its feathers are soaked, one wing trembles and fear has made every movement dangerous. It does not know your intention. You must decide what your presence will mean.',
        'A young griffin trapped beneath a collapsed cedar roadside shelter, wet feathers and a leather strap caught around a fallen branch, a traveler and several people keeping careful distance in soft forest rain.',
        [
          option('Place water within reach, keep your distance and look for signs of injury before touching the strap.', { caregiver: 2, hero: 2 }, { protection: 2 }, { protective: 2 }, { empathy: 2 }, { self_sacrifice: 1 }),
          option('Study the griffin’s movements until you understand which branch is holding the tension.', { sage: 2, magician: 2 }, { knowledge: 2 }, { rational: 1, intuitive: 1 }, { curiosity: 2 }),
          option('Build a clear corridor from cloth and branches so the creature has a safe direction once freed.', { creator: 2, explorer: 2 }, { creation: 1, freedom: 1 }, { strategic: 2 }, { autonomy: 1, persistence: 1 }),
          option('Ask everyone to step back, lower their voices and allow calm to return before anyone acts.', { innocent: 2, everyman: 2 }, { connection: 1, protection: 1 }, { protective: 1, intuitive: 1 }, { social_trust: 1, empathy: 1 }),
        ],
        true,
      ),
      scene(
        8,
        4,
        'The Coast Beneath the Moon',
        'When the griffin is free, it disappears between the cedars without looking back. At sunset, the forest opens onto the coast, and you see the Lighthouse of Vigil for the first time. It rises from a black island across a narrow channel. A fishing camp rests on a high stone terrace, preparing for the full moon. The wind is shifting, and the fishers warn that the lower paths may vanish beneath the tide before midnight.',
        'First panoramic view of the Lighthouse of Vigil on a black island at sunset, full moon rising above the sea, an elevated fishing camp on a stone terrace, travelers arriving from a cedar forest.',
        [
          option('Check the exits and high ground, then decide which low paths should close before the water rises.', { ruler: 2, outlaw: 2 }, { power: 1, protection: 1 }, { dominant: 1, strategic: 1 }, { autonomy: 1 }, { control: 1 }),
          option('Study the coastline and the lighthouse from every available vantage point before darkness settles.', { explorer: 2, innocent: 2 }, { freedom: 1, knowledge: 1 }, { intuitive: 1, rational: 1 }, { curiosity: 2 }),
          option('Help carry the last belongings from the lower platforms before the route becomes unsafe.', { hero: 2, caregiver: 2 }, { protection: 2 }, { impulsive: 1, protective: 1 }, { persistence: 2 }),
          option('Gather the arriving travelers, share food and make sure no one prepares for the night alone.', { everyman: 2, lover: 2 }, { connection: 2 }, { protective: 1, intuitive: 1 }, { empathy: 2, social_trust: 1 }),
        ],
      ),
      scene(
        9,
        4,
        'The Rising Tide',
        'The warning comes true. Moonlight turns the channel silver as waves cover the unloading platform and cut off the lowest stair. The camp remains safe above, but several people are still climbing with children, supplies and soaked packs. No monster has caused this danger, and no victory will stop the sea. What matters is the place you take while everyone reaches the same high ground.',
        'A moonlit coastal tide flooding the lower stairs of an elevated fishing camp, travelers climbing with children and supplies, ropes stretched between safe stone terraces, the lighthouse shining across the channel.',
        [
          option('Hold the guide rope at the exposed edge so others can climb without losing their footing.', { hero: 2, caregiver: 2 }, { protection: 2 }, { impulsive: 1, protective: 1 }, { persistence: 2 }, { self_sacrifice: 1 }),
          option('Separate the flow of people and cargo so neither blocks the narrow stair.', { ruler: 2, hero: 2 }, { power: 1, protection: 1 }, { dominant: 1, strategic: 2 }, { persistence: 1 }, { control: 1 }),
          option('Stay beside a frightened traveler and keep speaking until the next step feels possible.', { jester: 2, lover: 2 }, { connection: 2 }, { protective: 1, intuitive: 1 }, { empathy: 2 }),
          option('Form a steady relay so each person carries only what can safely reach the next pair of hands.', { everyman: 2, jester: 2 }, { connection: 2 }, { strategic: 1, protective: 1 }, { social_trust: 1, persistence: 1 }),
        ],
        true,
      ),
      scene(
        10,
        5,
        'The Four Objects',
        'At low tide, a stone path opens toward the island. Halfway across, you enter a chamber carved into the cliff. Four objects rest beneath a single inscription: Take what you believe you need. Learn whether you can release it. There is a narrow dagger, an iron key, a vial of amber liquid and a weathered cloak. You may touch only one before the chamber opens again.',
        'A sea-cliff chamber lit by amber moonlight, four intriguing objects on separate stone plinths: a narrow dagger, an old iron key, a vial of glowing amber liquid and a weathered travel cloak.',
        [
          option('Choose the dagger: a clean edge for cutting through what tries to hold you back.', { outlaw: 2, hero: 2 }, { freedom: 2 }, { dominant: 1, impulsive: 1 }, { autonomy: 2 }, { rebellion: 1 }),
          option('Choose the key: an invitation to enter what has remained closed and unknown.', { explorer: 2, outlaw: 2 }, { freedom: 1, knowledge: 1 }, { intuitive: 1, strategic: 1 }, { curiosity: 2 }, { avoidance: 1 }),
          option('Choose the vial: a promise that perception can change before the world does.', { magician: 2, sage: 2 }, { knowledge: 1, creation: 1 }, { intuitive: 2 }, { curiosity: 2 }, { obsession: 1 }),
          option('Choose the cloak: protection that can cover you or be opened around someone else.', { caregiver: 2, lover: 2 }, { protection: 1, connection: 1 }, { protective: 2 }, { empathy: 2 }, { self_sacrifice: 1 }),
        ],
      ),
      scene(
        11,
        5,
        'The Guardian of the Path',
        'The same door opens for every choice. Beyond it, a faun waits beside a flat stone, carrying a lamp and a worn walking staff. He says the object was never payment and never a prize. It belongs to the road. Before he shows you the final ascent, you must place what you chose on the stone. The destination will not change. Only the manner in which you let go remains yours.',
        'A dignified faun guardian with a lantern and worn staff beside a moonlit cliff path, a flat ritual stone waiting for one of four journey objects, the lighthouse ascent visible beyond.',
        [
          option('Place the object down immediately and trust a ritual you do not yet understand.', { innocent: 2, caregiver: 2 }, { protection: 1, connection: 1 }, { intuitive: 2 }, { social_trust: 2 }),
          option('Ask what will happen to it and who may need it next, then place it on the stone.', { sage: 2, outlaw: 2 }, { knowledge: 2 }, { rational: 2 }, { curiosity: 1, autonomy: 1 }, { rebellion: 1 }),
          option('Mark where the object was found so the next traveler can understand its history, then release it.', { creator: 2, outlaw: 2 }, { creation: 1, freedom: 1 }, { strategic: 1, dominant: 1 }, { autonomy: 1, persistence: 1 }),
          option('Ask another traveler to place their hands beneath yours so letting go becomes a shared act.', { lover: 2, everyman: 2 }, { connection: 2 }, { protective: 1, intuitive: 1 }, { empathy: 1, social_trust: 1 }),
        ],
        true,
      ),
      scene(
        12,
        6,
        'The Feast of Those Who Arrived',
        'The faun guides every traveler along the same hidden stair and leaves before the lighthouse door. Inside, a long table holds bread, broth and fruit for those who have crossed the road. Faces from the bridge, the tower and the coast appear among strangers who carried different maps. No one asks for proof that you belong. Before the ceremony begins, there is time to decide how you enter this circle.',
        'Inside the ancient lighthouse, a long welcoming table with bread, broth and fruit, travelers from earlier scenes reunited among strangers, warm candlelight, wet cloaks drying, anticipation before a moonlit ceremony.',
        [
          option('Move the places until strangers and familiar faces share the table without rank.', { everyman: 2, outlaw: 2 }, { connection: 1, freedom: 1 }, { dominant: 1, protective: 1 }, { social_trust: 2 }),
          option('Accept the food and allow yourself to rest before demanding another answer from the road.', { innocent: 2, caregiver: 2 }, { protection: 2 }, { intuitive: 1, protective: 1 }, { social_trust: 1 }, { avoidance: 1 }),
          option('Share one moment that mattered to you and listen for what mattered to someone else.', { lover: 2, jester: 2 }, { connection: 2 }, { intuitive: 1, protective: 1 }, { empathy: 2 }),
          option('Tell the most absurd part of the journey and let the whole table breathe through laughter.', { jester: 2, innocent: 2 }, { connection: 1, freedom: 1 }, { intuitive: 2 }, { social_trust: 1, empathy: 1 }),
        ],
      ),
      scene(
        13,
        6,
        'The Unlit Lighthouse',
        'A caretaker interrupts the feast with quiet urgency. The lantern above has gone dark, and ships are already waiting beyond the reef. In the maintenance room, there is oil to carry, a bent lamp support, a schedule no one has agreed to and a wall of small reflectors. The light can return only through many different kinds of effort. Which work draws you first?',
        'The maintenance room of an ancient dark lighthouse, travelers working together among oil canisters, a bent brass lamp support, duty charts and many small mirrors waiting to reflect one flame.',
        [
          option('Carry the heaviest oil reserves upward and relieve the people already exhausted by the climb.', { hero: 2, caregiver: 2 }, { protection: 2 }, { impulsive: 1, protective: 1 }, { persistence: 2 }, { self_sacrifice: 1 }),
          option('Repair the lamp support with an unconventional brace made from the tools that remain.', { creator: 2, outlaw: 2 }, { creation: 2 }, { strategic: 1, intuitive: 1 }, { autonomy: 1, curiosity: 1 }),
          option('Coordinate the work into short shifts so the light can be maintained after tonight.', { ruler: 2, everyman: 2 }, { power: 1, connection: 1 }, { dominant: 1, strategic: 2 }, { persistence: 1 }, { control: 1 }),
          option('Arrange the small reflectors so one modest flame becomes enough to cross the sea.', { magician: 2, creator: 2 }, { creation: 2 }, { intuitive: 2 }, { curiosity: 1, persistence: 1 }),
        ],
        true,
      ),
      scene(
        14,
        7,
        'What You Leave for the Next Traveler',
        'The repaired lantern sends a wide beam across the water. Before the full-moon ceremony, the caretaker opens a weathered notebook filled with drawings, warnings and messages from those who arrived before you. There is one blank page left. Nothing you write will change tonight’s path, but it may become the first companion of someone who has not yet received their letter.',
        'A weathered travelers’ notebook open to its final blank page on a desk inside the now-lit lighthouse, handwritten maps and messages on earlier pages, moonlight and the lighthouse beam crossing the room.',
        [
          option('Write a message in many voices, leaving space for future travelers to add their own lines.', { everyman: 2, outlaw: 2 }, { connection: 1, freedom: 1 }, { dominant: 1, protective: 1 }, { social_trust: 2 }),
          option('Draw the difficult sections of the road and the small improvements that made passage possible.', { creator: 2, sage: 2 }, { creation: 1, knowledge: 1 }, { rational: 1, strategic: 1 }, { curiosity: 1, persistence: 1 }),
          option('Write a private letter about the moment that changed you most, addressed to whoever needs it.', { lover: 2, innocent: 2 }, { connection: 2 }, { intuitive: 1, protective: 1 }, { empathy: 2, social_trust: 1 }),
          option('Leave a riddle that turns one hard truth into something the next traveler will want to discover.', { jester: 2, magician: 2 }, { creation: 1, knowledge: 1 }, { intuitive: 2 }, { curiosity: 2 }),
        ],
      ),
      scene(
        15,
        7,
        'The Melody That Remembered You',
        'At midnight, the travelers enter a circular chamber open to the full moon. The masked flutist stands at its center, exactly as the merchant described. He looks at you as though this is not your first arrival and says, “This time, you made it all the way here.” Around you, the others fall silent. The door remains open, the lighthouse burns above and the flutist raises his instrument. Before the first note reaches you, how do you choose to meet it?',
        'Circular moonlit chamber inside the lighthouse, a mysterious masked flutist raising a silver flute at the center, travelers gathered in a quiet ring, the door open, hypnotic anticipation under a full moon.',
        [
          option('Listen without demanding that the melody explain itself before you allow it to reach you.', { innocent: 2, lover: 2 }, { connection: 2 }, { intuitive: 2 }, { social_trust: 2, empathy: 1 }),
          option('Remain near the open door, aware of your breathing and the space you still control.', { explorer: 2, outlaw: 2 }, { freedom: 2 }, { protective: 1, rational: 1 }, { autonomy: 2 }, { avoidance: 1 }),
          option('Observe the pauses, the rhythm and the reactions of the people around you.', { sage: 2, ruler: 2 }, { knowledge: 2 }, { rational: 2, strategic: 1 }, { curiosity: 1 }, { emotional_detachment: 1 }),
          option('Follow the rhythm with your fingers and take part without surrendering your awareness.', { magician: 2, creator: 2 }, { creation: 2 }, { intuitive: 2 }, { curiosity: 1, autonomy: 1 }, { obsession: 1 }),
        ],
      ),
    ],
  }),
);
