import { archetypeSchema, deepFreeze, type Archetype } from '../types.js';

const definitions: Archetype[] = [
  {
    id: 'innocent', slug: 'innocent', name: 'Innocent',
    short_description: 'Finds possibility in trust, simplicity and a future worth tending.',
    core_desire: 'To live with hope and a sense of safety', core_fear: 'Losing trust in what makes life worthwhile',
    core_motivation: 'Preserve the possibility of a good beginning',
    strengths: ['Keeps hope available in uncertain situations', 'Makes complex goals feel approachable', 'Offers trust without making connection a transaction', 'Notices what is still working'],
    shadow_traits: ['May overlook inconvenient evidence to preserve hope', 'May postpone necessary conflict', 'May expect reassurance before taking an unfamiliar step'],
    growth_direction: ['Pair a hopeful expectation with a concrete contingency', 'Practice expressing disagreement without abandoning trust', 'Let complexity coexist with a simple next step'],
    decision_patterns: ['Looks for a clear and constructive next move', 'Prefers plans that preserve continuity and trust'],
    relationship_patterns: ['Brings warmth and a willingness to begin again', 'Benefits from naming needs before disappointment accumulates'],
    leadership_patterns: ['Provides an accessible shared purpose', 'Needs partners who can challenge optimistic assumptions'],
    symbolic_keywords: ['dawn', 'hearth', 'seed', 'open sky'],
  },
  {
    id: 'explorer', slug: 'explorer', name: 'Explorer',
    short_description: 'Learns through movement, discovery and room to choose an independent path.',
    core_desire: 'Freedom to discover and become', core_fear: 'Confinement and a life defined entirely by others',
    core_motivation: 'Find possibilities beyond familiar boundaries',
    strengths: ['Finds alternatives when the obvious route closes', 'Adapts to unfamiliar circumstances', 'Acts without needing every uncertainty resolved', 'Protects space for independent judgment'],
    shadow_traits: ['May leave before a difficult commitment has matured', 'May confuse movement with meaningful change', 'May resist helpful structure because it feels restrictive'],
    growth_direction: ['Choose one commitment worth carrying into uncertainty', 'Distinguish exploration from escape before changing course', 'Share intentions so independence does not become absence'],
    decision_patterns: ['Tests possibilities through direct experience', 'Values autonomy when comparing alternatives'],
    relationship_patterns: ['Connects through shared discoveries', 'Needs room to move alongside dependable communication'],
    leadership_patterns: ['Opens new territory for a group', 'Benefits from explicit handoffs and follow-through'],
    symbolic_keywords: ['horizon', 'compass', 'trail', 'wind'],
  },
  {
    id: 'sage', slug: 'sage', name: 'Sage',
    short_description: 'Seeks understanding through observation, evidence and careful questions.',
    core_desire: 'To understand what is true and useful', core_fear: 'Acting on illusion or unexamined assumptions',
    core_motivation: 'Turn uncertainty into a more accurate understanding',
    strengths: ['Separates observations from assumptions', 'Finds patterns in complicated information', 'Asks questions that improve a group decision', 'Makes knowledge available to others'],
    shadow_traits: ['May keep researching beyond the point of usefulness', 'May retreat into analysis when emotional presence is needed', 'May underestimate knowledge gained through action'],
    growth_direction: ['Set a decision deadline before beginning research', 'Name the feeling as well as the explanation', 'Run a small experiment when certainty is unavailable'],
    decision_patterns: ['Examines evidence before committing', 'Revises a model when information changes'],
    relationship_patterns: ['Offers attention through curiosity and thoughtful conversation', 'Benefits from expressing care without needing to solve everything'],
    leadership_patterns: ['Clarifies the assumptions behind a plan', 'Must leave room for participation beyond expertise'],
    symbolic_keywords: ['lantern', 'archive', 'lens', 'constellation'],
  },
  {
    id: 'hero', slug: 'hero', name: 'Hero',
    short_description: 'Meets a difficult task with courage, effort and a willingness to take responsibility.',
    core_desire: 'To meet a meaningful challenge with capable action', core_fear: 'Being unable to act when something important is at stake',
    core_motivation: 'Build capability in service of a worthwhile task',
    strengths: ['Acts when hesitation carries a cost', 'Persists through a demanding task', 'Makes responsibility visible through action', 'Encourages others by taking a first step'],
    shadow_traits: ['May take on a challenge that belongs to someone else', 'May treat rest as something that must be earned', 'May turn disagreement into a test of resolve'],
    growth_direction: ['Ask whether the task needs effort, help or a different approach', 'Include recovery in the plan', 'Invite another person to lead a part of the challenge'],
    decision_patterns: ['Prioritizes a concrete response to immediate difficulty', 'Learns by testing capability against reality'],
    relationship_patterns: ['Shows care through reliability and action', 'Benefits from sharing uncertainty before trying to fix it'],
    leadership_patterns: ['Creates momentum under pressure', 'Needs to protect others from an unsustainable pace'],
    symbolic_keywords: ['bridge', 'flame', 'shield', 'summit'],
  },
  {
    id: 'outlaw', slug: 'outlaw', name: 'Outlaw',
    short_description: 'Questions rules that have stopped serving people and opens space for change.',
    core_desire: 'Freedom from constraints that no longer deserve consent', core_fear: 'Being controlled by an unquestioned system',
    core_motivation: 'Challenge the terms when accepted rules obscure alternatives',
    strengths: ['Recognizes when a convention has become an obstacle', 'Voices an uncomfortable but useful challenge', 'Defends room for dissent', 'Imagines change beyond small adjustments'],
    shadow_traits: ['May oppose a constraint before understanding its purpose', 'May define direction mainly through resistance', 'May leave repair to others after exposing a problem'],
    growth_direction: ['Describe the alternative alongside the objection', 'Choose which limits protect what you value', 'Stay involved in the work of rebuilding'],
    decision_patterns: ['Examines who benefits from the available choices', 'Will consider changing the rules of a dilemma'],
    relationship_patterns: ['Values honesty and mutual freedom', 'Benefits from distinguishing disagreement from an attempt to control'],
    leadership_patterns: ['Makes necessary dissent possible', 'Needs a constructive destination beyond disruption'],
    symbolic_keywords: ['broken seal', 'wild road', 'spark', 'unbound knot'],
  },
  {
    id: 'magician', slug: 'magician', name: 'Magician',
    short_description: 'Notices hidden connections and experiments with ways a situation could transform.',
    core_desire: 'To turn possibility into meaningful transformation', core_fear: 'Being unable to influence a change that matters',
    core_motivation: 'Connect insight and action to make something newly possible',
    strengths: ['Reframes a stuck problem', 'Connects ideas across different domains', 'Helps others imagine a different outcome', 'Experiments with the system behind an event'],
    shadow_traits: ['May become attached to an elegant explanation', 'May try to shape outcomes without enough shared understanding', 'May underestimate the ordinary work that change requires'],
    growth_direction: ['Test the smallest useful version of a transformation', 'Explain the process so others can choose their involvement', 'Value maintenance as part of change'],
    decision_patterns: ['Looks for an underlying pattern or a changeable assumption', 'Combines intuition with experiments'],
    relationship_patterns: ['Connects through possibility and shared growth', 'Benefits from accepting a person without continually trying to transform the relationship'],
    leadership_patterns: ['Offers a picture of what could become possible', 'Needs transparent steps and grounded feedback'],
    symbolic_keywords: ['prism', 'threshold', 'resonance', 'unlit beacon'],
  },
  {
    id: 'lover', slug: 'lover', name: 'Lover',
    short_description: 'Pays attention to connection, meaning and the particular qualities of a person or moment.',
    core_desire: 'To connect deeply with people and experiences', core_fear: 'Losing a meaningful connection or feeling unseen',
    core_motivation: 'Give attention to what makes connection worth sustaining',
    strengths: ['Notices the emotional significance of a moment', 'Builds trust through attentive presence', 'Brings care to the quality of a shared experience', 'Recognizes value beyond efficiency'],
    shadow_traits: ['May protect harmony at the expense of a clear need', 'May hold tightly to a connection when it needs space', 'May overextend to avoid disappointing someone'],
    growth_direction: ['Name one need without apologizing for having it', 'Allow space without interpreting it as rejection', 'Keep personal commitments alongside shared ones'],
    decision_patterns: ['Considers what a choice means for connection', 'Values depth of experience over breadth alone'],
    relationship_patterns: ['Offers sustained attention and emotional investment', 'Benefits from direct communication about boundaries'],
    leadership_patterns: ['Makes people feel seen in a shared task', 'Needs to balance particular relationships with fair group decisions'],
    symbolic_keywords: ['thread', 'shared fire', 'song', 'mirror'],
  },
  {
    id: 'creator', slug: 'creator', name: 'Creator',
    short_description: 'Turns an imagined possibility into something tangible, expressive or useful.',
    core_desire: 'To make something that carries meaning', core_fear: 'Having no room to express or realize an idea',
    core_motivation: 'Give form to an idea through experimentation and craft',
    strengths: ['Finds new combinations in limited materials', 'Learns through prototypes', 'Brings a distinctive perspective to a shared problem', 'Improves a possibility by making it concrete'],
    shadow_traits: ['May keep revising after the work is useful', 'May tie self-worth too closely to the finished work', 'May resist constraints that would help completion'],
    growth_direction: ['Define what finished means before the next revision', 'Share an early version with someone it could help', 'Use one constraint as a creative prompt'],
    decision_patterns: ['Looks for something that can be made or redesigned', 'Explores alternatives through hands-on iteration'],
    relationship_patterns: ['Connects through shared projects and expression', 'Benefits from offering attention beyond the work itself'],
    leadership_patterns: ['Makes experimentation available to a team', 'Needs a practical rhythm for finishing and sharing'],
    symbolic_keywords: ['loom', 'lens', 'workshop', 'unfinished map'],
  },
  {
    id: 'caregiver', slug: 'caregiver', name: 'Caregiver',
    short_description: 'Recognizes what needs support and makes protection practical.',
    core_desire: 'To help people and what matters remain supported', core_fear: 'Overlooking a need when help could have mattered',
    core_motivation: 'Sustain people and conditions that allow life to continue',
    strengths: ['Notices needs that a fast-moving group can miss', 'Makes help practical and specific', 'Creates continuity during disruption', 'Remembers the human cost of a decision'],
    shadow_traits: ['May carry responsibilities without checking consent or capacity', 'May put personal needs last for too long', 'May make it difficult for others to contribute by doing too much'],
    growth_direction: ['Ask what support is wanted before offering it', 'Choose a clear limit for the help you can sustain', 'Let another person contribute without correcting the method'],
    decision_patterns: ['Assesses who or what needs protection', 'Prioritizes a sustainable support structure'],
    relationship_patterns: ['Expresses care through consistent support', 'Benefits from asking for help as directly as offering it'],
    leadership_patterns: ['Protects the conditions in which people can work', 'Needs boundaries that prevent quiet overload'],
    symbolic_keywords: ['shelter', 'water', 'root', 'hearth'],
  },
  {
    id: 'jester', slug: 'jester', name: 'Jester',
    short_description: 'Finds movement through play, perspective and attention to the present moment.',
    core_desire: 'To experience aliveness and shared enjoyment', core_fear: 'A life narrowed to duty without room for play',
    core_motivation: 'Release a fixed perspective and make room for possibility now',
    strengths: ['Releases tension without needing every problem solved', 'Invites participation through play', 'Spots an unexpected angle', 'Keeps a group connected to the present'],
    shadow_traits: ['May use humor to move away from discomfort too quickly', 'May defer follow-through for a more appealing moment', 'May underestimate how seriously another person experiences a problem'],
    growth_direction: ['Ask whether the moment needs lightness or listening', 'Finish one small commitment before improvising the next', 'Let an uncomfortable feeling remain without immediately reframing it'],
    decision_patterns: ['Experiments with an unexpected or playful response', 'Looks for immediate opportunities to shift a stuck dynamic'],
    relationship_patterns: ['Connects through shared moments and humor', 'Benefits from making room for conversations without a quick release'],
    leadership_patterns: ['Lowers the cost of joining in', 'Needs explicit follow-through after a burst of energy'],
    symbolic_keywords: ['bell', 'ribbon', 'dance', 'unexpected door'],
  },
  {
    id: 'ruler', slug: 'ruler', name: 'Ruler',
    short_description: 'Creates order, direction and reliable conditions for a shared undertaking.',
    core_desire: 'To create a stable and effective shared order', core_fear: 'A preventable breakdown without clear responsibility',
    core_motivation: 'Coordinate resources and decisions toward a lasting result',
    strengths: ['Clarifies responsibility when a group is uncertain', 'Connects immediate tasks to a longer plan', 'Makes resources and trade-offs visible', 'Builds systems that can support continuity'],
    shadow_traits: ['May tighten control when shared understanding would help', 'May treat another method as a threat to reliability', 'May keep decisions centralized longer than necessary'],
    growth_direction: ['Delegate an outcome and allow a different method', 'Ask whose knowledge is missing from the plan', 'Make one rule easy to question and revise'],
    decision_patterns: ['Compares options through resources, roles and consequences', 'Seeks explicit commitments before coordination'],
    relationship_patterns: ['Shows care through reliability and planning', 'Benefits from sharing uncertainty without immediately organizing it'],
    leadership_patterns: ['Creates clear conditions for coordinated work', 'Needs feedback channels that do not depend on permission'],
    symbolic_keywords: ['beacon', 'circle', 'keystone', 'council table'],
  },
  {
    id: 'everyman', slug: 'everyman', name: 'Everyman',
    short_description: 'Builds belonging through participation, practical cooperation and shared ground.',
    core_desire: 'To belong and contribute alongside others', core_fear: 'Being excluded or separated from ordinary shared life',
    core_motivation: 'Make participation possible without requiring exceptional status',
    strengths: ['Finds common ground among different people', 'Makes a contribution feel accessible', 'Shares practical responsibility', 'Notices when someone is being left outside a group'],
    shadow_traits: ['May mute a useful difference to preserve belonging', 'May accept a familiar group norm without examining it', 'May wait for agreement when a personal choice is needed'],
    growth_direction: ['State a preference before seeking consensus', 'Make room for belonging that includes disagreement', 'Take one useful action without waiting for everyone to join'],
    decision_patterns: ['Looks for a workable shared approach', 'Values participation and practical fairness'],
    relationship_patterns: ['Connects through steady presence and shared routines', 'Benefits from letting personal differences be visible'],
    leadership_patterns: ['Invites ownership throughout a group', 'Needs a clear way to decide when consensus is unavailable'],
    symbolic_keywords: ['common road', 'table', 'relay', 'woven circle'],
  },
];

export const archetypes = deepFreeze(definitions.map(value => archetypeSchema.parse(value)));
export const archetypeByKey = deepFreeze(Object.fromEntries(archetypes.map(a => [a.slug, a])) as Record<Archetype['slug'], Archetype>);
